name: Deploy typescript package to npm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: SetUp/Node@v1
        name: Set up Node.js
        with:
          node-version: 16
          npm-version: 8
      - name: Install dependencies
        run: |
          npm install -D vitest
          scp ./openapi-generator-ignore/tsconfig.json ./
          npm install
      - name: Test SDK
        run: |
          npm run test
      - name: Build SDK
        run: |
          npm run build
      - name: Publish SDK
        run: |
          npm publish --token='${{ secrets.NPM_TOKEN }}'