/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AddEntitlementCreditResponse {
    /**
    * The amount to be added to the credit amount.
    */
    'creditAmountIncrement'?: number;
    'entitlementID'?: string;
    'entitlementTermID'?: string;
    /**
    * The new credit amount after the increment.
    */
    'newCreditAmount'?: number;
    'organizationID'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "creditAmountIncrement",
            "baseName": "creditAmountIncrement",
            "type": "number",
            "format": ""
        },
        {
            "name": "entitlementID",
            "baseName": "entitlementID",
            "type": "string",
            "format": ""
        },
        {
            "name": "entitlementTermID",
            "baseName": "entitlementTermID",
            "type": "string",
            "format": ""
        },
        {
            "name": "newCreditAmount",
            "baseName": "newCreditAmount",
            "type": "number",
            "format": ""
        },
        {
            "name": "organizationID",
            "baseName": "organizationID",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddEntitlementCreditResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
