/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlibabaMarketplaceProductShopInfoWangWang } from '../models/AlibabaMarketplaceProductShopInfoWangWang';
import { HttpFile } from '../http/http';

export class AlibabaMarketplaceProductShopInfoWangWangs {
    'wangWang'?: Array<AlibabaMarketplaceProductShopInfoWangWang>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "wangWang",
            "baseName": "WangWang",
            "type": "Array<AlibabaMarketplaceProductShopInfoWangWang>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlibabaMarketplaceProductShopInfoWangWangs.attributeTypeMap;
    }

    public constructor() {
    }
}
