/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlibabaMarketplaceProductExtras } from '../models/AlibabaMarketplaceProductExtras';
import { AlibabaMarketplaceProductShopInfo } from '../models/AlibabaMarketplaceProductShopInfo';
import { AlibabaMarketplaceProductSkus } from '../models/AlibabaMarketplaceProductSkus';
import { HttpFile } from '../http/http';

export class AlibabaMarketplaceProduct {
    'auditFailMsg'?: string;
    'auditStatus'?: string;
    'auditTime'?: number;
    'code'?: string;
    'description'?: string;
    'frontCategoryId'?: number;
    'gmtCreated'?: number;
    'gmtModified'?: number;
    'name'?: string;
    'picUrl'?: string;
    'productExtras'?: AlibabaMarketplaceProductExtras;
    'productSkus'?: AlibabaMarketplaceProductSkus;
    'requestId'?: string;
    'score'?: number;
    'shopInfo'?: AlibabaMarketplaceProductShopInfo;
    'shortDescription'?: string;
    'status'?: string;
    'supplierPk'?: number;
    'type'?: string;
    'useCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "auditFailMsg",
            "baseName": "AuditFailMsg",
            "type": "string",
            "format": ""
        },
        {
            "name": "auditStatus",
            "baseName": "AuditStatus",
            "type": "string",
            "format": ""
        },
        {
            "name": "auditTime",
            "baseName": "AuditTime",
            "type": "number",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "Code",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "Description",
            "type": "string",
            "format": ""
        },
        {
            "name": "frontCategoryId",
            "baseName": "FrontCategoryId",
            "type": "number",
            "format": ""
        },
        {
            "name": "gmtCreated",
            "baseName": "GmtCreated",
            "type": "number",
            "format": ""
        },
        {
            "name": "gmtModified",
            "baseName": "GmtModified",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "Name",
            "type": "string",
            "format": ""
        },
        {
            "name": "picUrl",
            "baseName": "PicUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "productExtras",
            "baseName": "ProductExtras",
            "type": "AlibabaMarketplaceProductExtras",
            "format": ""
        },
        {
            "name": "productSkus",
            "baseName": "ProductSkus",
            "type": "AlibabaMarketplaceProductSkus",
            "format": ""
        },
        {
            "name": "requestId",
            "baseName": "RequestId",
            "type": "string",
            "format": ""
        },
        {
            "name": "score",
            "baseName": "Score",
            "type": "number",
            "format": ""
        },
        {
            "name": "shopInfo",
            "baseName": "ShopInfo",
            "type": "AlibabaMarketplaceProductShopInfo",
            "format": ""
        },
        {
            "name": "shortDescription",
            "baseName": "ShortDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "Status",
            "type": "string",
            "format": ""
        },
        {
            "name": "supplierPk",
            "baseName": "SupplierPk",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "Type",
            "type": "string",
            "format": ""
        },
        {
            "name": "useCount",
            "baseName": "UseCount",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlibabaMarketplaceProduct.attributeTypeMap;
    }

    public constructor() {
    }
}
