/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AwsMarketplaceCatalogPricingTermRateCardConstraints } from '../models/AwsMarketplaceCatalogPricingTermRateCardConstraints';
import { AwsMarketplaceCatalogPricingTermRateCardItem } from '../models/AwsMarketplaceCatalogPricingTermRateCardItem';
import { AwsMarketplaceCatalogPricingTermRateCardSelector } from '../models/AwsMarketplaceCatalogPricingTermRateCardSelector';
import { HttpFile } from '../http/http';

export class AwsMarketplaceCatalogPricingTermRateCard {
    /**
    * Defines constraints on how the term can be configured by acceptors. Applicable only to ConfigurableUpfrontPricingTerm.
    */
    'constraints'?: AwsMarketplaceCatalogPricingTermRateCardConstraints;
    'rateCard'?: Array<AwsMarketplaceCatalogPricingTermRateCardItem>;
    /**
    * Selector is used to differentiate between the mutually exclusive rate cards in the same pricing term, to be selected by the buyer. Applicable only to ConfigurableUpfrontPricingTerm.
    */
    'selector'?: AwsMarketplaceCatalogPricingTermRateCardSelector;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "constraints",
            "baseName": "Constraints",
            "type": "AwsMarketplaceCatalogPricingTermRateCardConstraints",
            "format": ""
        },
        {
            "name": "rateCard",
            "baseName": "RateCard",
            "type": "Array<AwsMarketplaceCatalogPricingTermRateCardItem>",
            "format": ""
        },
        {
            "name": "selector",
            "baseName": "Selector",
            "type": "AwsMarketplaceCatalogPricingTermRateCardSelector",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AwsMarketplaceCatalogPricingTermRateCard.attributeTypeMap;
    }

    public constructor() {
    }
}
