/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AwsMarketplaceCatalogLegalTermDocumentType } from '../models/AwsMarketplaceCatalogLegalTermDocumentType';
import { HttpFile } from '../http/http';

export class AwsMarketplaceCatalogLegalTermDocument {
    'type'?: AwsMarketplaceCatalogLegalTermDocumentType;
    /**
    * A URL to the legal document for buyers to read. Required when Type is one of the following [CustomEula, CustomDsa].
    */
    'url'?: string;
    /**
    * Version of standard contracts provided by AWS Marketplace. Required when Type is one of the following [StandardEula, StandardDsa]. The version of StandardEula is \"2022-07-14\". The version of StandardDsa is \"2019-12-12\".
    */
    'version'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "Type",
            "type": "AwsMarketplaceCatalogLegalTermDocumentType",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "Url",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "Version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AwsMarketplaceCatalogLegalTermDocument.attributeTypeMap;
    }

    public constructor() {
    }
}


