/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum AwsMarketplaceCppoOpportunityTermType {
    AwsMarketplaceCppoOpportunityTermType_BuyerTargetingTerm = 'BuyerTargetingTerm',
    AwsMarketplaceCppoOpportunityTermType_UpdateAvailability = 'UpdateAvailability',
    AwsMarketplaceCppoOpportunityTermType_BuyerValidityTerm = 'BuyerValidityTerm',
    AwsMarketplaceCppoOpportunityTermType_BuyerLegalTerm = 'BuyerLegalTerm',
    AwsMarketplaceCppoOpportunityTermType_ResaleLegalTerm = 'ResaleLegalTerm',
    AwsMarketplaceCppoOpportunityTermType_ResaleUsageBasedPricingTerm = 'ResaleUsageBasedPricingTerm',
    AwsMarketplaceCppoOpportunityTermType_ResaleConfigurableUpfrontPricingTerm = 'ResaleConfigurableUpfrontPricingTerm',
    AwsMarketplaceCppoOpportunityTermType_ResaleFixedUpfrontPricingTerm = 'ResaleFixedUpfrontPricingTerm',
    AwsMarketplaceCppoOpportunityTermType_ResalePaymentScheduleTerm = 'ResalePaymentScheduleTerm'
}
