/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AwsMarketplaceCatalogPricingTermRateCardSelector {
    /**
    * At this time, only \"Duration\" is supported.
    */
    'type'?: string;
    /**
    * ISO 8601 duration format. For example, \"P1M\" represents one month.
    */
    'value'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "Type",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "Value",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AwsMarketplaceCatalogPricingTermRateCardSelector.attributeTypeMap;
    }

    public constructor() {
    }
}
