/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AwsMarketplaceEventBridgeEventAccount } from '../models/AwsMarketplaceEventBridgeEventAccount';
import { AwsMarketplaceEventBridgeEventOffer } from '../models/AwsMarketplaceEventBridgeEventOffer';
import { AwsMarketplaceEventBridgeEventProduct } from '../models/AwsMarketplaceEventBridgeEventProduct';
import { HttpFile } from '../http/http';

export class AwsMarketplaceEventBridgeEventDetail {
    'catalog'?: string;
    'eventCategory'?: string;
    'eventID'?: string;
    'eventName'?: string;
    'eventSource'?: string;
    'eventType'?: string;
    'eventVersion'?: string;
    'managementEvent'?: boolean;
    /**
    * The seller/ISV\'s AWS Account Id.
    */
    'manufacturer'?: AwsMarketplaceEventBridgeEventAccount;
    'offer'?: AwsMarketplaceEventBridgeEventOffer;
    'product'?: AwsMarketplaceEventBridgeEventProduct;
    'requestID'?: string;
    'requestParameters'?: any;
    'responseElements'?: any;
    /**
    * For private offer created by a channel partner, this is the channel partner\'s AWS Account Id. For private offer created by a seller/ISV, this is the seller/ISV\'s AWS Account Id.
    */
    'sellerOfRecord'?: AwsMarketplaceEventBridgeEventAccount;
    'targetedBuyerAccountIds'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "catalog",
            "baseName": "catalog",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventCategory",
            "baseName": "eventCategory",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventID",
            "baseName": "eventID",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventName",
            "baseName": "eventName",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventSource",
            "baseName": "eventSource",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventVersion",
            "baseName": "eventVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "managementEvent",
            "baseName": "managementEvent",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "AwsMarketplaceEventBridgeEventAccount",
            "format": ""
        },
        {
            "name": "offer",
            "baseName": "offer",
            "type": "AwsMarketplaceEventBridgeEventOffer",
            "format": ""
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "AwsMarketplaceEventBridgeEventProduct",
            "format": ""
        },
        {
            "name": "requestID",
            "baseName": "requestID",
            "type": "string",
            "format": ""
        },
        {
            "name": "requestParameters",
            "baseName": "requestParameters",
            "type": "any",
            "format": ""
        },
        {
            "name": "responseElements",
            "baseName": "responseElements",
            "type": "any",
            "format": ""
        },
        {
            "name": "sellerOfRecord",
            "baseName": "sellerOfRecord",
            "type": "AwsMarketplaceEventBridgeEventAccount",
            "format": ""
        },
        {
            "name": "targetedBuyerAccountIds",
            "baseName": "targetedBuyerAccountIds",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AwsMarketplaceEventBridgeEventDetail.attributeTypeMap;
    }

    public constructor() {
    }
}
