/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AwsMarketplaceMeteringTag } from '../models/AwsMarketplaceMeteringTag';
import { HttpFile } from '../http/http';

export class AwsMarketplaceMeteringUsageAllocation {
    /**
    * The total quantity allocated to this bucket of usage.
    */
    'allocatedUsageQuantity'?: number;
    /**
    * The set of tags that define the bucket of usage. For the bucket of items with no tags, this parameter can be left out.
    */
    'tags'?: Array<AwsMarketplaceMeteringTag>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "allocatedUsageQuantity",
            "baseName": "AllocatedUsageQuantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "Tags",
            "type": "Array<AwsMarketplaceMeteringTag>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AwsMarketplaceMeteringUsageAllocation.attributeTypeMap;
    }

    public constructor() {
    }
}
