/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum AwsMarketplaceCppoDiscountType {
    AwsMarketplaceCppoDiscountType_DISCOUNT_PERCENT = 'DISCOUNT_PERCENT',
    AwsMarketplaceCppoDiscountType_CUSTOM_PRICE = 'CUSTOM_PRICE',
    AwsMarketplaceCppoDiscountType_FLEXIBLE_PAYMENT_SCHEDULE = 'CUSTOM_PRICE_WITH_FPS'
}
