/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AwsMarketplaceMeteringUsageRecord } from '../models/AwsMarketplaceMeteringUsageRecord';
import { HttpFile } from '../http/http';

export class AwsMarketplaceMeteringBatchMeterUsageInput {
    /**
    * Product code is used to uniquely identify a product in AWS Marketplace. The product code should be the same as the one used during the publishing of a new product.
    */
    'productCode'?: string;
    /**
    * The set of UsageRecords to submit. BatchMeterUsage accepts up to 25 UsageRecords at a time.
    */
    'usageRecords'?: Array<AwsMarketplaceMeteringUsageRecord>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productCode",
            "baseName": "ProductCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "usageRecords",
            "baseName": "UsageRecords",
            "type": "Array<AwsMarketplaceMeteringUsageRecord>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AwsMarketplaceMeteringBatchMeterUsageInput.attributeTypeMap;
    }

    public constructor() {
    }
}
