/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AwsProductDeliveryOption } from '../models/AwsProductDeliveryOption';
import { HttpFile } from '../http/http';

export class AwsProductVersion {
    'creationDate'?: Date;
    'deliveryOptions'?: Array<AwsProductDeliveryOption>;
    'id'?: string;
    'releaseNotes'?: string;
    'versionTitle'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "creationDate",
            "baseName": "CreationDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deliveryOptions",
            "baseName": "DeliveryOptions",
            "type": "Array<AwsProductDeliveryOption>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "Id",
            "type": "string",
            "format": ""
        },
        {
            "name": "releaseNotes",
            "baseName": "ReleaseNotes",
            "type": "string",
            "format": ""
        },
        {
            "name": "versionTitle",
            "baseName": "VersionTitle",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AwsProductVersion.attributeTypeMap;
    }

    public constructor() {
    }
}
