/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimeUnit } from '../models/TimeUnit';
import { HttpFile } from '../http/http';

export class AwsProductDimension {
    'description'?: string;
    'key'?: string;
    /**
    * The term length for the commit amount, such as 6 months, or 1 year. The length is used together with timeUnit. Length and TimeUnit are only used for commit dimension.
    */
    'length'?: number;
    'name'?: string;
    /**
    * Below three fields are only used for pass data when create or update product\'s public offer pricing. Rate is only used for update public offer, becasue rate will be set as 0.01 when create new product.
    */
    'rate'?: number;
    'timeUnit'?: TimeUnit;
    'types'?: Array<string>;
    'unit'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "Description",
            "type": "string",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "Key",
            "type": "string",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "Length",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "Name",
            "type": "string",
            "format": ""
        },
        {
            "name": "rate",
            "baseName": "Rate",
            "type": "number",
            "format": ""
        },
        {
            "name": "timeUnit",
            "baseName": "TimeUnit",
            "type": "TimeUnit",
            "format": ""
        },
        {
            "name": "types",
            "baseName": "Types",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "Unit",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AwsProductDimension.attributeTypeMap;
    }

    public constructor() {
    }
}


