/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureMarketplacePrivateOfferBeneficiaryRecipient } from '../models/AzureMarketplacePrivateOfferBeneficiaryRecipient';
import { HttpFile } from '../http/http';

export class AzureMarketplacePrivateOfferBeneficiary {
    'beneficiaryRecipients'?: Array<AzureMarketplacePrivateOfferBeneficiaryRecipient>;
    'description'?: string;
    /**
    * the customer billing account id.
    */
    'id'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "beneficiaryRecipients",
            "baseName": "beneficiaryRecipients",
            "type": "Array<AzureMarketplacePrivateOfferBeneficiaryRecipient>",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplacePrivateOfferBeneficiary.attributeTypeMap;
    }

    public constructor() {
    }
}
