/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureADIdentifier } from '../models/AzureADIdentifier';
import { AzureMarketplaceSubscriptionStatus } from '../models/AzureMarketplaceSubscriptionStatus';
import { AzureTerm } from '../models/AzureTerm';
import { HttpFile } from '../http/http';

export class AzureMarketplaceSubscription {
    'allowedCustomerOperations'?: Array<AzureMarketplaceSubscriptionAllowedCustomerOperationsEnum>;
    'autoRenew'?: boolean;
    'beneficiary'?: AzureADIdentifier;
    'created'?: Date;
    'fulfillmentId'?: string;
    'id'?: string;
    'isFreeTrial'?: boolean;
    'isTest'?: boolean;
    'lastModified'?: string;
    'name'?: string;
    'offerId'?: string;
    'planId'?: string;
    'publisherId'?: string;
    'purchaser'?: AzureADIdentifier;
    'quantity'?: number;
    'saasSubscriptionStatus'?: AzureMarketplaceSubscriptionStatus;
    'sandboxType'?: AzureMarketplaceSubscriptionSandboxTypeEnum;
    'sessionId'?: string;
    'sessionMode'?: AzureMarketplaceSubscriptionSessionModeEnum;
    'storeFront'?: string;
    'term'?: AzureTerm;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "allowedCustomerOperations",
            "baseName": "allowedCustomerOperations",
            "type": "Array<AzureMarketplaceSubscriptionAllowedCustomerOperationsEnum>",
            "format": ""
        },
        {
            "name": "autoRenew",
            "baseName": "autoRenew",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "beneficiary",
            "baseName": "beneficiary",
            "type": "AzureADIdentifier",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "fulfillmentId",
            "baseName": "fulfillmentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isFreeTrial",
            "baseName": "isFreeTrial",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isTest",
            "baseName": "isTest",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastModified",
            "baseName": "lastModified",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "offerId",
            "baseName": "offerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "planId",
            "baseName": "planId",
            "type": "string",
            "format": ""
        },
        {
            "name": "publisherId",
            "baseName": "publisherId",
            "type": "string",
            "format": ""
        },
        {
            "name": "purchaser",
            "baseName": "purchaser",
            "type": "AzureADIdentifier",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "saasSubscriptionStatus",
            "baseName": "saasSubscriptionStatus",
            "type": "AzureMarketplaceSubscriptionStatus",
            "format": ""
        },
        {
            "name": "sandboxType",
            "baseName": "sandboxType",
            "type": "AzureMarketplaceSubscriptionSandboxTypeEnum",
            "format": ""
        },
        {
            "name": "sessionId",
            "baseName": "sessionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "sessionMode",
            "baseName": "sessionMode",
            "type": "AzureMarketplaceSubscriptionSessionModeEnum",
            "format": ""
        },
        {
            "name": "storeFront",
            "baseName": "storeFront",
            "type": "string",
            "format": ""
        },
        {
            "name": "term",
            "baseName": "term",
            "type": "AzureTerm",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplaceSubscription.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AzureMarketplaceSubscriptionAllowedCustomerOperationsEnum {
    Read = 'Read',
    Update = 'Update',
    Delete = 'Delete'
}
export enum AzureMarketplaceSubscriptionSandboxTypeEnum {
    None = 'None',
    Csp = 'Csp'
}
export enum AzureMarketplaceSubscriptionSessionModeEnum {
    None = 'None',
    DryRun = 'DryRun'
}

