/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureMarketplaceOfferPricingType } from '../models/AzureMarketplaceOfferPricingType';
import { AzureMarketplacePrivateOfferAcceptanceLink } from '../models/AzureMarketplacePrivateOfferAcceptanceLink';
import { AzureMarketplacePrivateOfferBeneficiary } from '../models/AzureMarketplacePrivateOfferBeneficiary';
import { AzureMarketplacePrivateOfferPartner } from '../models/AzureMarketplacePrivateOfferPartner';
import { AzureMarketplacePrivateOfferPricing } from '../models/AzureMarketplacePrivateOfferPricing';
import { AzureMarketplacePrivateOfferPromotionReference } from '../models/AzureMarketplacePrivateOfferPromotionReference';
import { AzureMarketplacePrivateOfferState } from '../models/AzureMarketplacePrivateOfferState';
import { AzureMarketplacePrivateOfferSubState } from '../models/AzureMarketplacePrivateOfferSubState';
import { AzureMarketplacePrivateOfferTermsDoc } from '../models/AzureMarketplacePrivateOfferTermsDoc';
import { AzureMarketplacePrivateOfferType } from '../models/AzureMarketplacePrivateOfferType';
import { AzureMarketplaceValidation } from '../models/AzureMarketplaceValidation';
import { HttpFile } from '../http/http';

export class AzureMarketplacePrivateOffer {
    'schema'?: string;
    /**
    * in format YYYY-MM-DD
    */
    'acceptBy'?: Date;
    'acceptanceLinks'?: Array<AzureMarketplacePrivateOfferAcceptanceLink>;
    'beneficiaries'?: Array<AzureMarketplacePrivateOfferBeneficiary>;
    /**
    * If true, it is a renewal offer for an existing customer.
    */
    'customerContractRenewal'?: boolean;
    'eTag'?: string;
    /**
    * in format YYYY-MM-DD
    */
    'end'?: Date;
    /**
    * in format of \"private-offer/private-offer-durable-id\"
    */
    'id'?: string;
    /**
    * in format YYYY-MM-DD
    */
    'lastModified'?: Date;
    'name'?: string;
    /**
    * array of email addresses of the users to be notified of any changes in the private offer status.
    */
    'notificationContacts'?: Array<string>;
    'offerPricingType'?: AzureMarketplaceOfferPricingType;
    'partners'?: Array<AzureMarketplacePrivateOfferPartner>;
    'preparedBy'?: string;
    /**
    * Up to 10 pricing entries are allowed.
    */
    'pricing'?: Array<AzureMarketplacePrivateOfferPricing>;
    'privateOfferType'?: AzureMarketplacePrivateOfferType;
    'resourceName'?: string;
    /**
    * in format YYYY-MM-DD, if VariableStartDate = true, this field should be empty.
    */
    'start'?: Date;
    'state'?: AzureMarketplacePrivateOfferState;
    'subState'?: AzureMarketplacePrivateOfferSubState;
    /**
    * Only applicable to private offers with privateOfferType = customerPromotion || cspPromotion
    */
    'termsAndConditionsDocSasUrl'?: string;
    /**
    * Only applicable to private offers with privateOfferType = multipartyPromotionOriginator || multipartyPromotionChannelPartner
    */
    'termsAndConditionsDocs'?: Array<AzureMarketplacePrivateOfferTermsDoc>;
    'upgradedFrom'?: AzureMarketplacePrivateOfferPromotionReference;
    'validations'?: Array<AzureMarketplaceValidation>;
    'variableStartDate'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": ""
        },
        {
            "name": "acceptBy",
            "baseName": "acceptBy",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "acceptanceLinks",
            "baseName": "acceptanceLinks",
            "type": "Array<AzureMarketplacePrivateOfferAcceptanceLink>",
            "format": ""
        },
        {
            "name": "beneficiaries",
            "baseName": "beneficiaries",
            "type": "Array<AzureMarketplacePrivateOfferBeneficiary>",
            "format": ""
        },
        {
            "name": "customerContractRenewal",
            "baseName": "customerContractRenewal",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "eTag",
            "baseName": "eTag",
            "type": "string",
            "format": ""
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastModified",
            "baseName": "lastModified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "notificationContacts",
            "baseName": "notificationContacts",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "offerPricingType",
            "baseName": "offerPricingType",
            "type": "AzureMarketplaceOfferPricingType",
            "format": ""
        },
        {
            "name": "partners",
            "baseName": "partners",
            "type": "Array<AzureMarketplacePrivateOfferPartner>",
            "format": ""
        },
        {
            "name": "preparedBy",
            "baseName": "preparedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "pricing",
            "baseName": "pricing",
            "type": "Array<AzureMarketplacePrivateOfferPricing>",
            "format": ""
        },
        {
            "name": "privateOfferType",
            "baseName": "privateOfferType",
            "type": "AzureMarketplacePrivateOfferType",
            "format": ""
        },
        {
            "name": "resourceName",
            "baseName": "resourceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "AzureMarketplacePrivateOfferState",
            "format": ""
        },
        {
            "name": "subState",
            "baseName": "subState",
            "type": "AzureMarketplacePrivateOfferSubState",
            "format": ""
        },
        {
            "name": "termsAndConditionsDocSasUrl",
            "baseName": "termsAndConditionsDocSasUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "termsAndConditionsDocs",
            "baseName": "termsAndConditionsDocs",
            "type": "Array<AzureMarketplacePrivateOfferTermsDoc>",
            "format": ""
        },
        {
            "name": "upgradedFrom",
            "baseName": "upgradedFrom",
            "type": "AzureMarketplacePrivateOfferPromotionReference",
            "format": ""
        },
        {
            "name": "validations",
            "baseName": "validations",
            "type": "Array<AzureMarketplaceValidation>",
            "format": ""
        },
        {
            "name": "variableStartDate",
            "baseName": "variableStartDate",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplacePrivateOffer.attributeTypeMap;
    }

    public constructor() {
    }
}


