/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AzureProductPackageConfiguration {
    'azureActiveDirectoryApplicationID'?: string;
    'azureActiveDirectoryTenantID'?: string;
    'connectionWebhook'?: string;
    'id'?: string;
    'landingPageUri'?: string;
    'resourceType'?: AzureProductPackageConfigurationResourceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "azureActiveDirectoryApplicationID",
            "baseName": "azureActiveDirectoryApplicationID",
            "type": "string",
            "format": ""
        },
        {
            "name": "azureActiveDirectoryTenantID",
            "baseName": "azureActiveDirectoryTenantID",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionWebhook",
            "baseName": "connectionWebhook",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "landingPageUri",
            "baseName": "landingPageUri",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourceType",
            "baseName": "resourceType",
            "type": "AzureProductPackageConfigurationResourceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureProductPackageConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AzureProductPackageConfigurationResourceTypeEnum {
    AzureSoftwareAsAServicePackageConfiguration = 'AzureSoftwareAsAServicePackageConfiguration'
}

