/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureLocalizedTimeRange } from '../models/AzureLocalizedTimeRange';
import { HttpFile } from '../http/http';

export class AzureProductVariantTrial {
    'dateTimeRange'?: AzureLocalizedTimeRange;
    'duration'?: number;
    'durationType'?: AzureProductVariantTrialDurationTypeEnum;
    'type'?: AzureProductVariantTrialTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dateTimeRange",
            "baseName": "dateTimeRange",
            "type": "AzureLocalizedTimeRange",
            "format": ""
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number",
            "format": ""
        },
        {
            "name": "durationType",
            "baseName": "durationType",
            "type": "AzureProductVariantTrialDurationTypeEnum",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AzureProductVariantTrialTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureProductVariantTrial.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AzureProductVariantTrialDurationTypeEnum {
    Minute = 'Minute',
    Days = 'Days',
    Months = 'Months'
}
export enum AzureProductVariantTrialTypeEnum {
    NoTrial = 'NoTrial',
    TimedAccess = 'TimedAccess',
    TimedUsage = 'TimedUsage',
    Unlimited = 'Unlimited'
}

