/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureMarketplaceDeprecationScheduleAlternative } from '../models/AzureMarketplaceDeprecationScheduleAlternative';
import { HttpFile } from '../http/http';

export class AzureMarketplaceDeprecationSchedule {
    'schema'?: string;
    'alternative'?: AzureMarketplaceDeprecationScheduleAlternative;
    /**
    * format: date-time
    */
    'date'?: string;
    /**
    * format: duration
    */
    'dateOffset'?: string;
    'reason'?: AzureMarketplaceDeprecationScheduleReasonEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": ""
        },
        {
            "name": "alternative",
            "baseName": "alternative",
            "type": "AzureMarketplaceDeprecationScheduleAlternative",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateOffset",
            "baseName": "dateOffset",
            "type": "string",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "AzureMarketplaceDeprecationScheduleReasonEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplaceDeprecationSchedule.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AzureMarketplaceDeprecationScheduleReasonEnum {
    CriticalSecurityIssue = 'criticalSecurityIssue',
    EndOfSupport = 'endOfSupport',
    Other = 'other'
}

