/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzurePrice } from '../models/AzurePrice';
import { AzurePriceCadence } from '../models/AzurePriceCadence';
import { AzurePricingUnit } from '../models/AzurePricingUnit';
import { HttpFile } from '../http/http';

export class AzurePriceSchedule {
    'priceCadence'?: AzurePriceCadence;
    'pricingModel'?: AzurePriceSchedulePricingModelEnum;
    'pricingUnits'?: Array<AzurePricingUnit>;
    'retailPrice'?: AzurePrice;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "priceCadence",
            "baseName": "priceCadence",
            "type": "AzurePriceCadence",
            "format": ""
        },
        {
            "name": "pricingModel",
            "baseName": "pricingModel",
            "type": "AzurePriceSchedulePricingModelEnum",
            "format": ""
        },
        {
            "name": "pricingUnits",
            "baseName": "pricingUnits",
            "type": "Array<AzurePricingUnit>",
            "format": ""
        },
        {
            "name": "retailPrice",
            "baseName": "retailPrice",
            "type": "AzurePrice",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzurePriceSchedule.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AzurePriceSchedulePricingModelEnum {
    Flat = 'Flat',
    Recurring = 'Recurring',
    Usage = 'Usage'
}

