/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum AzureMarketplaceSubscriptionStatus {
    AzureMarketplaceSubscriptionStatus_NotStarted = 'NotStarted',
    AzureMarketplaceSubscriptionStatus_PendingFulfillmentStart = 'PendingFulfillmentStart',
    AzureMarketplaceSubscriptionStatus_Subscribed = 'Subscribed',
    AzureMarketplaceSubscriptionStatus_Suspended = 'Suspended',
    AzureMarketplaceSubscriptionStatus_Unsubscribed = 'Unsubscribed'
}
