/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureMarketplaceIdentity } from '../models/AzureMarketplaceIdentity';
import { AzureMarketplaceProductType } from '../models/AzureMarketplaceProductType';
import { AzureMarketplaceResourceLifecycleState } from '../models/AzureMarketplaceResourceLifecycleState';
import { AzureMarketplaceValidation } from '../models/AzureMarketplaceValidation';
import { HttpFile } from '../http/http';

export class AzureMarketplaceProduct {
    'schema'?: string;
    /**
    * The Product Display Name
    */
    'alias'?: string;
    /**
    * in format of \"product/product-durable-id\"
    */
    'id'?: string;
    'identity'?: AzureMarketplaceIdentity;
    'lifecycleState'?: AzureMarketplaceResourceLifecycleState;
    'productGroup'?: string;
    'resourceName'?: string;
    'type'?: AzureMarketplaceProductType;
    'validations'?: Array<AzureMarketplaceValidation>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": ""
        },
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "identity",
            "baseName": "identity",
            "type": "AzureMarketplaceIdentity",
            "format": ""
        },
        {
            "name": "lifecycleState",
            "baseName": "lifecycleState",
            "type": "AzureMarketplaceResourceLifecycleState",
            "format": ""
        },
        {
            "name": "productGroup",
            "baseName": "productGroup",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourceName",
            "baseName": "resourceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AzureMarketplaceProductType",
            "format": ""
        },
        {
            "name": "validations",
            "baseName": "validations",
            "type": "Array<AzureMarketplaceValidation>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplaceProduct.attributeTypeMap;
    }

    public constructor() {
    }
}


