/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureCommercialMarketplaceSetup } from '../models/AzureCommercialMarketplaceSetup';
import { AzureMarketplaceCustomerLeads } from '../models/AzureMarketplaceCustomerLeads';
import { AzureMarketplaceListing } from '../models/AzureMarketplaceListing';
import { AzureMarketplaceListingAsset } from '../models/AzureMarketplaceListingAsset';
import { AzureMarketplacePlanResource } from '../models/AzureMarketplacePlanResource';
import { AzureMarketplacePriceAndAvailabilityCustomMeter } from '../models/AzureMarketplacePriceAndAvailabilityCustomMeter';
import { AzureMarketplacePriceAndAvailabilityOffer } from '../models/AzureMarketplacePriceAndAvailabilityOffer';
import { AzureMarketplaceProduct } from '../models/AzureMarketplaceProduct';
import { AzureMarketplaceProperty } from '../models/AzureMarketplaceProperty';
import { AzureMarketplaceReseller } from '../models/AzureMarketplaceReseller';
import { AzureMarketplaceSaasTechnicalConfiguration } from '../models/AzureMarketplaceSaasTechnicalConfiguration';
import { AzureMarketplaceSubmission } from '../models/AzureMarketplaceSubmission';
import { HttpFile } from '../http/http';

export class AzureMarketplaceProductResource {
    'customerLeads'?: AzureMarketplaceCustomerLeads;
    'listing'?: AzureMarketplaceListing;
    'listingAssets'?: Array<AzureMarketplaceListingAsset>;
    'plans'?: Array<AzureMarketplacePlanResource>;
    'priceAndAvailabilityCustomMeter'?: AzureMarketplacePriceAndAvailabilityCustomMeter;
    'priceAndAvailabilityOffer'?: AzureMarketplacePriceAndAvailabilityOffer;
    'product'?: AzureMarketplaceProduct;
    'property'?: AzureMarketplaceProperty;
    'reseller'?: AzureMarketplaceReseller;
    'setup'?: AzureCommercialMarketplaceSetup;
    'submission'?: AzureMarketplaceSubmission;
    'technicalConfiguration'?: AzureMarketplaceSaasTechnicalConfiguration;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customerLeads",
            "baseName": "customerLeads",
            "type": "AzureMarketplaceCustomerLeads",
            "format": ""
        },
        {
            "name": "listing",
            "baseName": "listing",
            "type": "AzureMarketplaceListing",
            "format": ""
        },
        {
            "name": "listingAssets",
            "baseName": "listingAssets",
            "type": "Array<AzureMarketplaceListingAsset>",
            "format": ""
        },
        {
            "name": "plans",
            "baseName": "plans",
            "type": "Array<AzureMarketplacePlanResource>",
            "format": ""
        },
        {
            "name": "priceAndAvailabilityCustomMeter",
            "baseName": "priceAndAvailabilityCustomMeter",
            "type": "AzureMarketplacePriceAndAvailabilityCustomMeter",
            "format": ""
        },
        {
            "name": "priceAndAvailabilityOffer",
            "baseName": "priceAndAvailabilityOffer",
            "type": "AzureMarketplacePriceAndAvailabilityOffer",
            "format": ""
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "AzureMarketplaceProduct",
            "format": ""
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "AzureMarketplaceProperty",
            "format": ""
        },
        {
            "name": "reseller",
            "baseName": "reseller",
            "type": "AzureMarketplaceReseller",
            "format": ""
        },
        {
            "name": "setup",
            "baseName": "setup",
            "type": "AzureCommercialMarketplaceSetup",
            "format": ""
        },
        {
            "name": "submission",
            "baseName": "submission",
            "type": "AzureMarketplaceSubmission",
            "format": ""
        },
        {
            "name": "technicalConfiguration",
            "baseName": "technicalConfiguration",
            "type": "AzureMarketplaceSaasTechnicalConfiguration",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplaceProductResource.attributeTypeMap;
    }

    public constructor() {
    }
}
