/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AzureMarketplacePriceBillingSchedule {
    /**
    * In format of YYYY-MM-DD.
    */
    'chargeDate'?: string;
    'note'?: string;
    'pricePerPaymentInUsd'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chargeDate",
            "baseName": "chargeDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "pricePerPaymentInUsd",
            "baseName": "pricePerPaymentInUsd",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplacePriceBillingSchedule.attributeTypeMap;
    }

    public constructor() {
    }
}
