/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureMarketplacePriceAndAvailabilityCustomMeterItem } from '../models/AzureMarketplacePriceAndAvailabilityCustomMeterItem';
import { AzureMarketplaceValidation } from '../models/AzureMarketplaceValidation';
import { HttpFile } from '../http/http';

export class AzureMarketplacePriceAndAvailabilityCustomMeter {
    'schema'?: string;
    'customMeters'?: { [key: string]: AzureMarketplacePriceAndAvailabilityCustomMeterItem; };
    'id'?: string;
    'product'?: string;
    'resourceName'?: string;
    'validations'?: Array<AzureMarketplaceValidation>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": ""
        },
        {
            "name": "customMeters",
            "baseName": "customMeters",
            "type": "{ [key: string]: AzureMarketplacePriceAndAvailabilityCustomMeterItem; }",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourceName",
            "baseName": "resourceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "validations",
            "baseName": "validations",
            "type": "Array<AzureMarketplaceValidation>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplacePriceAndAvailabilityCustomMeter.attributeTypeMap;
    }

    public constructor() {
    }
}
