/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AzureMarketplacePreviewAudience {
    'description'?: string;
    'resourceId'?: string;
    'type'?: AzureMarketplacePreviewAudienceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourceId",
            "baseName": "resourceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AzureMarketplacePreviewAudienceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplacePreviewAudience.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AzureMarketplacePreviewAudienceTypeEnum {
    Subscription = 'subscription'
}

