/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureMarketplacePlan } from '../models/AzureMarketplacePlan';
import { AzureMarketplacePlanListing } from '../models/AzureMarketplacePlanListing';
import { AzureMarketplacePriceAndAvailabilityPlan } from '../models/AzureMarketplacePriceAndAvailabilityPlan';
import { HttpFile } from '../http/http';

export class AzureMarketplacePlanResource {
    'plan'?: AzureMarketplacePlan;
    'planListing'?: AzureMarketplacePlanListing;
    'priceAndAvailabilityPlan'?: AzureMarketplacePriceAndAvailabilityPlan;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "plan",
            "baseName": "plan",
            "type": "AzureMarketplacePlan",
            "format": ""
        },
        {
            "name": "planListing",
            "baseName": "planListing",
            "type": "AzureMarketplacePlanListing",
            "format": ""
        },
        {
            "name": "priceAndAvailabilityPlan",
            "baseName": "priceAndAvailabilityPlan",
            "type": "AzureMarketplacePriceAndAvailabilityPlan",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplacePlanResource.attributeTypeMap;
    }

    public constructor() {
    }
}
