/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureMarketplacePriceBillingSchedule } from '../models/AzureMarketplacePriceBillingSchedule';
import { AzureMarketplacePriceInitialCharge } from '../models/AzureMarketplacePriceInitialCharge';
import { HttpFile } from '../http/http';

export class AzureMarketplacePriceFlexibleSchedule {
    'billingSchedule'?: Array<AzureMarketplacePriceBillingSchedule>;
    'initialCharge'?: AzureMarketplacePriceInitialCharge;
    'price'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billingSchedule",
            "baseName": "billingSchedule",
            "type": "Array<AzureMarketplacePriceBillingSchedule>",
            "format": ""
        },
        {
            "name": "initialCharge",
            "baseName": "initialCharge",
            "type": "AzureMarketplacePriceInitialCharge",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplacePriceFlexibleSchedule.attributeTypeMap;
    }

    public constructor() {
    }
}
