/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureMarketplacePriceAndAvailabilityAudience } from '../models/AzureMarketplacePriceAndAvailabilityAudience';
import { AzureMarketplacePriceAndAvailabilityPrice } from '../models/AzureMarketplacePriceAndAvailabilityPrice';
import { AzureMarketplacePriceAndAvailabilitySoftwareReservation } from '../models/AzureMarketplacePriceAndAvailabilitySoftwareReservation';
import { AzureMarketplaceTerm } from '../models/AzureMarketplaceTerm';
import { AzureMarketplaceValidation } from '../models/AzureMarketplaceValidation';
import { HttpFile } from '../http/http';

export class AzureMarketplacePriceAndAvailabilityPlan {
    'schema'?: string;
    'audience'?: AzureMarketplacePriceAndAvailabilityPlanAudienceEnum;
    'billingTag'?: string;
    'id'?: string;
    'markets'?: Array<string>;
    'meterDefine'?: string;
    'plan'?: string;
    'pricing'?: AzureMarketplacePriceAndAvailabilityPrice;
    'privateAudiences'?: Array<AzureMarketplacePriceAndAvailabilityAudience>;
    'product'?: string;
    'resourceName'?: string;
    'softwareReservation'?: Array<AzureMarketplacePriceAndAvailabilitySoftwareReservation>;
    'trial'?: AzureMarketplaceTerm;
    'validations'?: Array<AzureMarketplaceValidation>;
    'visibility'?: AzureMarketplacePriceAndAvailabilityPlanVisibilityEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": ""
        },
        {
            "name": "audience",
            "baseName": "audience",
            "type": "AzureMarketplacePriceAndAvailabilityPlanAudienceEnum",
            "format": ""
        },
        {
            "name": "billingTag",
            "baseName": "billingTag",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "markets",
            "baseName": "markets",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "meterDefine",
            "baseName": "meterDefine",
            "type": "string",
            "format": ""
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "string",
            "format": ""
        },
        {
            "name": "pricing",
            "baseName": "pricing",
            "type": "AzureMarketplacePriceAndAvailabilityPrice",
            "format": ""
        },
        {
            "name": "privateAudiences",
            "baseName": "privateAudiences",
            "type": "Array<AzureMarketplacePriceAndAvailabilityAudience>",
            "format": ""
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourceName",
            "baseName": "resourceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "softwareReservation",
            "baseName": "softwareReservation",
            "type": "Array<AzureMarketplacePriceAndAvailabilitySoftwareReservation>",
            "format": ""
        },
        {
            "name": "trial",
            "baseName": "trial",
            "type": "AzureMarketplaceTerm",
            "format": ""
        },
        {
            "name": "validations",
            "baseName": "validations",
            "type": "Array<AzureMarketplaceValidation>",
            "format": ""
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "AzureMarketplacePriceAndAvailabilityPlanVisibilityEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplacePriceAndAvailabilityPlan.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AzureMarketplacePriceAndAvailabilityPlanAudienceEnum {
    Public = 'public',
    Private = 'private'
}
export enum AzureMarketplacePriceAndAvailabilityPlanVisibilityEnum {
    Visible = 'visible',
    Hidden = 'hidden'
}

