/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureMarketplaceResourceLifecycleState } from '../models/AzureMarketplaceResourceLifecycleState';
import { AzureMarketplaceValidation } from '../models/AzureMarketplaceValidation';
import { HttpFile } from '../http/http';

export class AzureMarketplacePlanListing {
    'schema'?: string;
    'description'?: string;
    'id'?: string;
    'kind'?: AzureMarketplacePlanListingKindEnum;
    'languageId'?: string;
    'lifecycleState'?: AzureMarketplaceResourceLifecycleState;
    'name'?: string;
    'plan'?: string;
    'product'?: string;
    'resourceName'?: string;
    'summary'?: string;
    'validations'?: Array<AzureMarketplaceValidation>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "AzureMarketplacePlanListingKindEnum",
            "format": ""
        },
        {
            "name": "languageId",
            "baseName": "languageId",
            "type": "string",
            "format": ""
        },
        {
            "name": "lifecycleState",
            "baseName": "lifecycleState",
            "type": "AzureMarketplaceResourceLifecycleState",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "string",
            "format": ""
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourceName",
            "baseName": "resourceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "validations",
            "baseName": "validations",
            "type": "Array<AzureMarketplaceValidation>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplacePlanListing.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AzureMarketplacePlanListingKindEnum {
    AzureVmPlan = 'azureVM-plan',
    AzureSaaSPlan = 'azureSaaS-plan',
    AzureCoreVmPlan = 'azureCoreVM-plan',
    AzureContainerPlan = 'azureContainer-plan'
}

