/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureListingContact } from '../models/AzureListingContact';
import { AzureListingUri } from '../models/AzureListingUri';
import { AzureProductListingAsset } from '../models/AzureProductListingAsset';
import { HttpFile } from '../http/http';

export class AzureProductListing {
    'accessInformation'?: string;
    /**
    * Not original fields. They are populated by other API calls
    */
    'assets'?: Array<AzureProductListingAsset>;
    'compatibleProducts'?: Array<string>;
    'description'?: string;
    'gettingStartedInstructions'?: string;
    'id'?: string;
    'keywords'?: Array<string>;
    'languageCode'?: string;
    'listingContacts'?: Array<AzureListingContact>;
    'listingUris'?: Array<AzureListingUri>;
    'productDisplayName'?: string;
    'publisherName'?: string;
    'resourceType'?: AzureProductListingResourceTypeEnum;
    'shortDescription'?: string;
    'summary'?: string;
    'title'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessInformation",
            "baseName": "accessInformation",
            "type": "string",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<AzureProductListingAsset>",
            "format": ""
        },
        {
            "name": "compatibleProducts",
            "baseName": "compatibleProducts",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "gettingStartedInstructions",
            "baseName": "gettingStartedInstructions",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "languageCode",
            "baseName": "languageCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "listingContacts",
            "baseName": "listingContacts",
            "type": "Array<AzureListingContact>",
            "format": ""
        },
        {
            "name": "listingUris",
            "baseName": "listingUris",
            "type": "Array<AzureListingUri>",
            "format": ""
        },
        {
            "name": "productDisplayName",
            "baseName": "productDisplayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "publisherName",
            "baseName": "publisherName",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourceType",
            "baseName": "resourceType",
            "type": "AzureProductListingResourceTypeEnum",
            "format": ""
        },
        {
            "name": "shortDescription",
            "baseName": "shortDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureProductListing.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AzureProductListingResourceTypeEnum {
    AzureListing = 'AzureListing'
}

