/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AzureMarketplaceResourceTarget {
    'targetId'?: string;
    'targetType'?: AzureMarketplaceResourceTargetTargetTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "targetId",
            "baseName": "targetId",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetType",
            "baseName": "targetType",
            "type": "AzureMarketplaceResourceTargetTargetTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplaceResourceTarget.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AzureMarketplaceResourceTargetTargetTypeEnum {
    Flight = 'flight',
    Sandbox = 'sandbox',
    Draft = 'draft',
    Preview = 'preview',
    Live = 'live',
    Certification = 'certification',
    Retail = 'retail'
}

