/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureLocalizedTimeRange } from '../models/AzureLocalizedTimeRange';
import { AzurePriceSchedule } from '../models/AzurePriceSchedule';
import { HttpFile } from '../http/http';

export class AzureProductVariantPriceSchedule {
    'dateTimeRange'?: AzureLocalizedTimeRange;
    'friendlyName'?: string;
    /**
    * There is only one base schedule.
    */
    'isBaseSchedule'?: boolean;
    /**
    * ISO country code
    */
    'marketCodes'?: Array<string>;
    'schedules'?: Array<AzurePriceSchedule>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dateTimeRange",
            "baseName": "dateTimeRange",
            "type": "AzureLocalizedTimeRange",
            "format": ""
        },
        {
            "name": "friendlyName",
            "baseName": "friendlyName",
            "type": "string",
            "format": ""
        },
        {
            "name": "isBaseSchedule",
            "baseName": "isBaseSchedule",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "marketCodes",
            "baseName": "marketCodes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "schedules",
            "baseName": "schedules",
            "type": "Array<AzurePriceSchedule>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureProductVariantPriceSchedule.attributeTypeMap;
    }

    public constructor() {
    }
}
