/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AzureMarketplacePriceAndAvailabilitySoftwareReservation {
    /**
    * default 0
    */
    'percentageSave'?: number;
    /**
    * default 0
    */
    'term'?: number;
    'type'?: AzureMarketplacePriceAndAvailabilitySoftwareReservationTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "percentageSave",
            "baseName": "percentageSave",
            "type": "number",
            "format": ""
        },
        {
            "name": "term",
            "baseName": "term",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AzureMarketplacePriceAndAvailabilitySoftwareReservationTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureMarketplacePriceAndAvailabilitySoftwareReservation.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AzureMarketplacePriceAndAvailabilitySoftwareReservationTypeEnum {
    Month = 'month',
    Year = 'year'
}

