/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BillingInvoiceInfo } from '../models/BillingInvoiceInfo';
import { BillingInvoiceStatus } from '../models/BillingInvoiceStatus';
import { BillingInvoiceType } from '../models/BillingInvoiceType';
import { BillingPaymentStatus } from '../models/BillingPaymentStatus';
import { HttpFile } from '../http/http';

export class BillingInvoice {
    'buyerID'?: string;
    'creationTime'?: Date;
    'endDate'?: Date;
    'entitlementID'?: string;
    'id'?: string;
    'info'?: BillingInvoiceInfo;
    /**
    * The invoice file URL, provided as AWS S3 presigned URL with expiration time. Output only.
    */
    'invoiceURL'?: string;
    'lastUpdateTime'?: Date;
    'organizationID'?: string;
    'paymentStatus'?: BillingPaymentStatus;
    'startDate'?: Date;
    'status'?: BillingInvoiceStatus;
    'type'?: BillingInvoiceType;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "buyerID",
            "baseName": "buyerID",
            "type": "string",
            "format": ""
        },
        {
            "name": "creationTime",
            "baseName": "creationTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "entitlementID",
            "baseName": "entitlementID",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "info",
            "baseName": "info",
            "type": "BillingInvoiceInfo",
            "format": ""
        },
        {
            "name": "invoiceURL",
            "baseName": "invoiceURL",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastUpdateTime",
            "baseName": "lastUpdateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "organizationID",
            "baseName": "organizationID",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentStatus",
            "baseName": "paymentStatus",
            "type": "BillingPaymentStatus",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BillingInvoiceStatus",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BillingInvoiceType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BillingInvoice.attributeTypeMap;
    }

    public constructor() {
    }
}


