/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StripeBalanceTransaction } from '../models/StripeBalanceTransaction';
import { StripeDispute } from '../models/StripeDispute';
import { StripeError } from '../models/StripeError';
import { StripePaymentIntent } from '../models/StripePaymentIntent';
import { StripeRefund } from '../models/StripeRefund';
import { HttpFile } from '../http/http';

export class BillingPaymentTransactionInfo {
    /**
    * The invoice issue date.
    */
    'invoiceDate'?: Date;
    /**
    * Refund flag marks whether the transaction has any refund records.
    */
    'refundExists'?: boolean;
    /**
    * Balance transaction that describes the impact of this charge on your account balance.
    */
    'stripeBalanceTransaction'?: StripeBalanceTransaction;
    /**
    * Stripe dispute result, got by Dispute API, there may be multiple disputes.
    */
    'stripeDisputes'?: Array<StripeDispute>;
    /**
    * Error of stripe API call
    */
    'stripeError'?: StripeError;
    /**
    * Stripe payment intent result, got by PaymentIntent API
    */
    'stripePaymentIntent'?: StripePaymentIntent;
    /**
    * Stripe refund result, got by Refund API
    */
    'stripeRefund'?: StripeRefund;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "invoiceDate",
            "baseName": "invoiceDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "refundExists",
            "baseName": "refundExists",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "stripeBalanceTransaction",
            "baseName": "stripeBalanceTransaction",
            "type": "StripeBalanceTransaction",
            "format": ""
        },
        {
            "name": "stripeDisputes",
            "baseName": "stripeDisputes",
            "type": "Array<StripeDispute>",
            "format": ""
        },
        {
            "name": "stripeError",
            "baseName": "stripeError",
            "type": "StripeError",
            "format": ""
        },
        {
            "name": "stripePaymentIntent",
            "baseName": "stripePaymentIntent",
            "type": "StripePaymentIntent",
            "format": ""
        },
        {
            "name": "stripeRefund",
            "baseName": "stripeRefund",
            "type": "StripeRefund",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BillingPaymentTransactionInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
