/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeteringUsageRecordGroupByKey } from '../models/MeteringUsageRecordGroupByKey';
import { HttpFile } from '../http/http';

export class BillableDimensionUsageDailyRevenue {
    'billableMetricKey'?: MeteringUsageRecordGroupByKey;
    'date'?: string;
    'quantity'?: number;
    'uniquePropertyItems'?: { [key: string]: any; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billableMetricKey",
            "baseName": "billableMetricKey",
            "type": "MeteringUsageRecordGroupByKey",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "uniquePropertyItems",
            "baseName": "uniquePropertyItems",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BillableDimensionUsageDailyRevenue.attributeTypeMap;
    }

    public constructor() {
    }
}
