/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum BillableMetricFilterOperation {
    BillableMetricFilterOperation_IS = 'IS',
    BillableMetricFilterOperation_NOT_IS = 'NOT_IS',
    BillableMetricFilterOperation_CONTAINS = 'CONTAINS',
    BillableMetricFilterOperation_NOT_CONTAINS = 'NOT_CONTAINS',
    BillableMetricFilterOperation_GT = 'GT',
    BillableMetricFilterOperation_GTE = 'GTE',
    BillableMetricFilterOperation_LT = 'LT',
    BillableMetricFilterOperation_LTE = 'LTE',
    BillableMetricFilterOperation_EQ = 'EQ',
    BillableMetricFilterOperation_NEQ = 'NOT_EQ',
    BillableMetricFilterOperation_EXISTS = 'EXISTS',
    BillableMetricFilterOperation_NOT_EXISTS = 'NOT_EXISTS'
}
