/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClientDescribeInstanceResponseBodyModules } from '../models/ClientDescribeInstanceResponseBodyModules';
import { ClientDescribeInstanceResponseBodyRelationalData } from '../models/ClientDescribeInstanceResponseBodyRelationalData';
import { HttpFile } from '../http/http';

export class ClientDescribeInstanceResponseBody {
    'appJson'?: string;
    'autoRenewal'?: string;
    'beganOn'?: number;
    'componentJson'?: string;
    'constraints'?: string;
    'createdOn'?: number;
    'endOn'?: number;
    'extendJson'?: string;
    'hostJson'?: string;
    'instanceId'?: number;
    'isTrial'?: boolean;
    'modules'?: ClientDescribeInstanceResponseBodyModules;
    'orderId'?: number;
    'productCode'?: string;
    'productName'?: string;
    'productSkuCode'?: string;
    'productType'?: string;
    'relationalData'?: ClientDescribeInstanceResponseBodyRelationalData;
    'status'?: string;
    'supplierName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appJson",
            "baseName": "AppJson",
            "type": "string",
            "format": ""
        },
        {
            "name": "autoRenewal",
            "baseName": "AutoRenewal",
            "type": "string",
            "format": ""
        },
        {
            "name": "beganOn",
            "baseName": "BeganOn",
            "type": "number",
            "format": ""
        },
        {
            "name": "componentJson",
            "baseName": "ComponentJson",
            "type": "string",
            "format": ""
        },
        {
            "name": "constraints",
            "baseName": "Constraints",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdOn",
            "baseName": "CreatedOn",
            "type": "number",
            "format": ""
        },
        {
            "name": "endOn",
            "baseName": "EndOn",
            "type": "number",
            "format": ""
        },
        {
            "name": "extendJson",
            "baseName": "ExtendJson",
            "type": "string",
            "format": ""
        },
        {
            "name": "hostJson",
            "baseName": "HostJson",
            "type": "string",
            "format": ""
        },
        {
            "name": "instanceId",
            "baseName": "InstanceId",
            "type": "number",
            "format": ""
        },
        {
            "name": "isTrial",
            "baseName": "IsTrial",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "modules",
            "baseName": "Modules",
            "type": "ClientDescribeInstanceResponseBodyModules",
            "format": ""
        },
        {
            "name": "orderId",
            "baseName": "OrderId",
            "type": "number",
            "format": ""
        },
        {
            "name": "productCode",
            "baseName": "ProductCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "productName",
            "baseName": "ProductName",
            "type": "string",
            "format": ""
        },
        {
            "name": "productSkuCode",
            "baseName": "ProductSkuCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "productType",
            "baseName": "ProductType",
            "type": "string",
            "format": ""
        },
        {
            "name": "relationalData",
            "baseName": "RelationalData",
            "type": "ClientDescribeInstanceResponseBodyRelationalData",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "Status",
            "type": "string",
            "format": ""
        },
        {
            "name": "supplierName",
            "baseName": "SupplierName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClientDescribeInstanceResponseBody.attributeTypeMap;
    }

    public constructor() {
    }
}
