/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum EntitlementStatus {
    EntitlementStatus_UNKNOWN = '',
    EntitlementStatus_ACTIVE = 'ACTIVE',
    EntitlementStatus_CANCELLED = 'CANCELLED',
    EntitlementStatus_DELETED = 'DELETED',
    EntitlementStatus_PENDING_CANCEL = 'PENDING_CANCEL',
    EntitlementStatus_PENDING_START = 'PENDING_START',
    EntitlementStatus_SUSPENDED = 'SUSPENDED'
}
