/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpAmountUnit } from '../models/GcpAmountUnit';
import { HttpFile } from '../http/http';

export class GcpAmountConstraint {
    'defaultAmount'?: GcpAmountUnit;
    'maxAmount'?: GcpAmountUnit;
    'minAmount'?: GcpAmountUnit;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "defaultAmount",
            "baseName": "defaultAmount",
            "type": "GcpAmountUnit",
            "format": ""
        },
        {
            "name": "maxAmount",
            "baseName": "maxAmount",
            "type": "GcpAmountUnit",
            "format": ""
        },
        {
            "name": "minAmount",
            "baseName": "minAmount",
            "type": "GcpAmountUnit",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpAmountConstraint.attributeTypeMap;
    }

    public constructor() {
    }
}
