/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GcpMarketplaceProductInfo {
    /**
    * The service level (price plan) with time duration suffix, such as \"basic-plan-P1Y\"
    */
    'flavorExternalName'?: string;
    'productExternalName'?: string;
    'providerId'?: string;
    /**
    * The price plan, such as \"basic-plan\"
    */
    'serviceLevel'?: string;
    'serviceName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "flavorExternalName",
            "baseName": "flavorExternalName",
            "type": "string",
            "format": ""
        },
        {
            "name": "productExternalName",
            "baseName": "productExternalName",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerId",
            "baseName": "providerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceLevel",
            "baseName": "serviceLevel",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceName",
            "baseName": "serviceName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplaceProductInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
