/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum GcpMarketplaceEntitlementState {
    GcpMarketplaceEntitlementState_ENTITLEMENT_STATE_UNSPECIFIED = 'ENTITLEMENT_STATE_UNSPECIFIED',
    GcpMarketplaceEntitlementState_ENTITLEMENT_ACTIVATION_REQUESTED = 'ENTITLEMENT_ACTIVATION_REQUESTED',
    GcpMarketplaceEntitlementState_ENTITLEMENT_ACTIVE = 'ENTITLEMENT_ACTIVE',
    GcpMarketplaceEntitlementState_ENTITLEMENT_PENDING_CANCELLATION = 'ENTITLEMENT_PENDING_CANCELLATION',
    GcpMarketplaceEntitlementState_ENTITLEMENT_CANCELLED = 'ENTITLEMENT_CANCELLED',
    GcpMarketplaceEntitlementState_ENTITLEMENT_PENDING_PLAN_CHANGE = 'ENTITLEMENT_PENDING_PLAN_CHANGE',
    GcpMarketplaceEntitlementState_ENTITLEMENT_PENDING_PLAN_CHANGE_APPROVAL = 'ENTITLEMENT_PENDING_PLAN_CHANGE_APPROVAL',
    GcpMarketplaceEntitlementState_ENTITLEMENT_SUSPENDED = 'ENTITLEMENT_SUSPENDED'
}
