/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpMarketplaceAgreementDocument } from '../models/GcpMarketplaceAgreementDocument';
import { GcpMarketplaceEntitlement } from '../models/GcpMarketplaceEntitlement';
import { GcpMarketplaceExistingOfferData } from '../models/GcpMarketplaceExistingOfferData';
import { GcpMarketplacePrivateOfferCustomerInfo } from '../models/GcpMarketplacePrivateOfferCustomerInfo';
import { GcpMarketplacePrivateOfferInstallmentTimeline } from '../models/GcpMarketplacePrivateOfferInstallmentTimeline';
import { GcpMarketplacePrivateOfferMetricInformation } from '../models/GcpMarketplacePrivateOfferMetricInformation';
import { GcpMarketplacePrivateOfferMigrationMetadata } from '../models/GcpMarketplacePrivateOfferMigrationMetadata';
import { GcpMarketplacePrivateOfferPriceModel } from '../models/GcpMarketplacePrivateOfferPriceModel';
import { GcpMarketplacePrivateOfferPriceModelType } from '../models/GcpMarketplacePrivateOfferPriceModelType';
import { GcpMarketplacePrivateOfferProviderInfo } from '../models/GcpMarketplacePrivateOfferProviderInfo';
import { GcpMarketplacePrivateOfferReplacementMetadata } from '../models/GcpMarketplacePrivateOfferReplacementMetadata';
import { GcpMarketplacePrivateOfferState } from '../models/GcpMarketplacePrivateOfferState';
import { GcpMarketplacePrivateOfferTerm } from '../models/GcpMarketplacePrivateOfferTerm';
import { GcpMarketplaceProductFeatureValue } from '../models/GcpMarketplaceProductFeatureValue';
import { GcpMarketplacePurchaseChannel } from '../models/GcpMarketplacePurchaseChannel';
import { GcpMarketplaceResellerInfo } from '../models/GcpMarketplaceResellerInfo';
import { PaymentScheduleType } from '../models/PaymentScheduleType';
import { HttpFile } from '../http/http';

export class GcpMarketplacePrivateOffer {
    'activeEntitlement'?: GcpMarketplaceEntitlement;
    'agencyEnabled'?: boolean;
    /**
    * The resource name of agreement(entitlement) In format of \"projects/{projectNumber}/agreements/{agreementId}\"
    */
    'agreement'?: string;
    'agreementDocuments'?: GcpMarketplaceAgreementDocument;
    'cancelTime'?: Date;
    'customerInfo'?: GcpMarketplacePrivateOfferCustomerInfo;
    'existingOfferData'?: GcpMarketplaceExistingOfferData;
    'expireTime'?: Date;
    'features'?: Array<GcpMarketplaceProductFeatureValue>;
    'installmentTimeline'?: GcpMarketplacePrivateOfferInstallmentTimeline;
    /**
    * such as \"PUBLISHED\"
    */
    'lifecycleState'?: string;
    'metricInformation'?: GcpMarketplacePrivateOfferMetricInformation;
    'migrationMetadata'?: GcpMarketplacePrivateOfferMigrationMetadata;
    /**
    * In format of \"projects/{projectNumber}/services/{serviceName, such as service-name.endpoints.gcp-project-id.cloud.goog}/privateOffers/{privateOfferId}\"
    */
    'name'?: string;
    /**
    * GCP private offer ID
    */
    'offerId'?: string;
    /**
    * such as \"OFFER\" or \"RESOLD\" (resold via channel partner)
    */
    'offerSource'?: GcpMarketplacePrivateOfferOfferSourceEnum;
    'offerState'?: GcpMarketplacePrivateOfferState;
    'offerTerm'?: GcpMarketplacePrivateOfferTerm;
    /**
    * The offer title in the GCP Marketplace.
    */
    'offerTitle'?: string;
    'offerTitleAutoGenerated'?: boolean;
    /**
    * such as \"PREPAY\" or \"POSTPAY\"
    */
    'paymentSchedule'?: PaymentScheduleType;
    'policies'?: { [key: string]: string; };
    /**
    * Nill if the offer has payment installments.
    */
    'priceModel'?: GcpMarketplacePrivateOfferPriceModel;
    'priceModelType'?: GcpMarketplacePrivateOfferPriceModelType;
    'providerCancellationInternalNote'?: string;
    'providerInfo'?: GcpMarketplacePrivateOfferProviderInfo;
    'providerInternalNote'?: string;
    'providerPublicNote'?: string;
    'purchaseChannel'?: GcpMarketplacePurchaseChannel;
    'purchaseTime'?: Date;
    'replacementMetadata'?: GcpMarketplacePrivateOfferReplacementMetadata;
    /**
    * The info of the reseller who resold the offer and when OfferSource is \"RESOLD\".
    */
    'resellerInfo'?: GcpMarketplaceResellerInfo;
    /**
    * The Plan of the offer.
    */
    'serviceLevel'?: string;
    'updateTime'?: Date;
    'useLegacyPartnerEula'?: boolean;
    'userLabels'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "activeEntitlement",
            "baseName": "activeEntitlement",
            "type": "GcpMarketplaceEntitlement",
            "format": ""
        },
        {
            "name": "agencyEnabled",
            "baseName": "agencyEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "agreement",
            "baseName": "agreement",
            "type": "string",
            "format": ""
        },
        {
            "name": "agreementDocuments",
            "baseName": "agreementDocuments",
            "type": "GcpMarketplaceAgreementDocument",
            "format": ""
        },
        {
            "name": "cancelTime",
            "baseName": "cancelTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "customerInfo",
            "baseName": "customerInfo",
            "type": "GcpMarketplacePrivateOfferCustomerInfo",
            "format": ""
        },
        {
            "name": "existingOfferData",
            "baseName": "existingOfferData",
            "type": "GcpMarketplaceExistingOfferData",
            "format": ""
        },
        {
            "name": "expireTime",
            "baseName": "expireTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "Array<GcpMarketplaceProductFeatureValue>",
            "format": ""
        },
        {
            "name": "installmentTimeline",
            "baseName": "installmentTimeline",
            "type": "GcpMarketplacePrivateOfferInstallmentTimeline",
            "format": ""
        },
        {
            "name": "lifecycleState",
            "baseName": "lifecycleState",
            "type": "string",
            "format": ""
        },
        {
            "name": "metricInformation",
            "baseName": "metricInformation",
            "type": "GcpMarketplacePrivateOfferMetricInformation",
            "format": ""
        },
        {
            "name": "migrationMetadata",
            "baseName": "migrationMetadata",
            "type": "GcpMarketplacePrivateOfferMigrationMetadata",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "offerId",
            "baseName": "offerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "offerSource",
            "baseName": "offerSource",
            "type": "GcpMarketplacePrivateOfferOfferSourceEnum",
            "format": ""
        },
        {
            "name": "offerState",
            "baseName": "offerState",
            "type": "GcpMarketplacePrivateOfferState",
            "format": ""
        },
        {
            "name": "offerTerm",
            "baseName": "offerTerm",
            "type": "GcpMarketplacePrivateOfferTerm",
            "format": ""
        },
        {
            "name": "offerTitle",
            "baseName": "offerTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "offerTitleAutoGenerated",
            "baseName": "offerTitleAutoGenerated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "paymentSchedule",
            "baseName": "paymentSchedule",
            "type": "PaymentScheduleType",
            "format": ""
        },
        {
            "name": "policies",
            "baseName": "policies",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "priceModel",
            "baseName": "priceModel",
            "type": "GcpMarketplacePrivateOfferPriceModel",
            "format": ""
        },
        {
            "name": "priceModelType",
            "baseName": "priceModelType",
            "type": "GcpMarketplacePrivateOfferPriceModelType",
            "format": ""
        },
        {
            "name": "providerCancellationInternalNote",
            "baseName": "providerCancellationInternalNote",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerInfo",
            "baseName": "providerInfo",
            "type": "GcpMarketplacePrivateOfferProviderInfo",
            "format": ""
        },
        {
            "name": "providerInternalNote",
            "baseName": "providerInternalNote",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerPublicNote",
            "baseName": "providerPublicNote",
            "type": "string",
            "format": ""
        },
        {
            "name": "purchaseChannel",
            "baseName": "purchaseChannel",
            "type": "GcpMarketplacePurchaseChannel",
            "format": ""
        },
        {
            "name": "purchaseTime",
            "baseName": "purchaseTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "replacementMetadata",
            "baseName": "replacementMetadata",
            "type": "GcpMarketplacePrivateOfferReplacementMetadata",
            "format": ""
        },
        {
            "name": "resellerInfo",
            "baseName": "resellerInfo",
            "type": "GcpMarketplaceResellerInfo",
            "format": ""
        },
        {
            "name": "serviceLevel",
            "baseName": "serviceLevel",
            "type": "string",
            "format": ""
        },
        {
            "name": "updateTime",
            "baseName": "updateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "useLegacyPartnerEula",
            "baseName": "useLegacyPartnerEula",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "userLabels",
            "baseName": "userLabels",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplacePrivateOffer.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum GcpMarketplacePrivateOfferOfferSourceEnum {
    Offer = 'OFFER',
    Resold = 'RESOLD'
}

