/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum GcpMarketplacePrivateOfferState {
    GcpMarketplacePrivateOfferState_OFFER_ACTIVE = 'OFFER_ACTIVE',
    GcpMarketplacePrivateOfferState_OFFER_ACTIVATING = 'OFFER_ACTIVATING',
    GcpMarketplacePrivateOfferState_OFFER_SCHEDULED = 'OFFER_SCHEDULED',
    GcpMarketplacePrivateOfferState_OFFER_ENTITLEMENT_ACCOUNT_PENDING = 'OFFER_ENTITLEMENT_ACCOUNT_PENDING',
    GcpMarketplacePrivateOfferState_OFFER_PUBLISHED = 'OFFER_PUBLISHED',
    GcpMarketplacePrivateOfferState_OFFER_LAPSED = 'OFFER_LAPSED',
    GcpMarketplacePrivateOfferState_OFFER_EXPIRED = 'OFFER_EXPIRED',
    GcpMarketplacePrivateOfferState_OFFER_CANCELLED = 'OFFER_CANCELLED',
    GcpMarketplacePrivateOfferState_OFFER_UNAVAILABLE = 'OFFER_UNAVAILABLE',
    GcpMarketplacePrivateOfferState_OFFER_DRAFT = 'OFFER_DRAFT',
    GcpMarketplacePrivateOfferState_OFFER_APPROVAL_FAILED = 'OFFER_APPROVAL_FAILED'
}
