/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpMarketplacePriceModel } from '../models/GcpMarketplacePriceModel';
import { GcpMarketplaceProductSubscriptionPlan } from '../models/GcpMarketplaceProductSubscriptionPlan';
import { GcpMarketplaceProductUsageFee } from '../models/GcpMarketplaceProductUsageFee';
import { HttpFile } from '../http/http';

export class GcpMarketplaceProductPriceInfo {
    'description'?: string;
    'priceModel'?: GcpMarketplacePriceModel;
    /**
    * Subscription Plan (Flat Commitment)
    */
    'subscriptionPlans'?: Array<GcpMarketplaceProductSubscriptionPlan>;
    /**
    * Usage Metering Dimension/Metric if available
    */
    'usageFees'?: Array<GcpMarketplaceProductUsageFee>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "priceModel",
            "baseName": "priceModel",
            "type": "GcpMarketplacePriceModel",
            "format": ""
        },
        {
            "name": "subscriptionPlans",
            "baseName": "subscriptionPlans",
            "type": "Array<GcpMarketplaceProductSubscriptionPlan>",
            "format": ""
        },
        {
            "name": "usageFees",
            "baseName": "usageFees",
            "type": "Array<GcpMarketplaceProductUsageFee>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplaceProductPriceInfo.attributeTypeMap;
    }

    public constructor() {
    }
}


