/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpMarketplaceEntitlement } from '../models/GcpMarketplaceEntitlement';
import { GcpMarketplaceExistingPrivateOffer } from '../models/GcpMarketplaceExistingPrivateOffer';
import { GcpMarketplacePrivateOfferPriceModelType } from '../models/GcpMarketplacePrivateOfferPriceModelType';
import { HttpFile } from '../http/http';

export class GcpMarketplaceExistingOfferData {
    'entitlement'?: GcpMarketplaceEntitlement;
    'existingPriceModelType'?: GcpMarketplacePrivateOfferPriceModelType;
    'hasEntitlementChanged'?: boolean;
    'privateOffer'?: GcpMarketplaceExistingPrivateOffer;
    'standardOffer'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "entitlement",
            "baseName": "entitlement",
            "type": "GcpMarketplaceEntitlement",
            "format": ""
        },
        {
            "name": "existingPriceModelType",
            "baseName": "existingPriceModelType",
            "type": "GcpMarketplacePrivateOfferPriceModelType",
            "format": ""
        },
        {
            "name": "hasEntitlementChanged",
            "baseName": "hasEntitlementChanged",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "privateOffer",
            "baseName": "privateOffer",
            "type": "GcpMarketplaceExistingPrivateOffer",
            "format": ""
        },
        {
            "name": "standardOffer",
            "baseName": "standardOffer",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplaceExistingOfferData.attributeTypeMap;
    }

    public constructor() {
    }
}


