/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpMarketplaceOfferStartPolicy } from '../models/GcpMarketplaceOfferStartPolicy';
import { GcpPeriodDuration } from '../models/GcpPeriodDuration';
import { HttpFile } from '../http/http';

export class GcpMarketplacePrivateOfferTerm {
    'enableScheduledStartTimes'?: boolean;
    'endTime'?: Date;
    'startPolicy'?: GcpMarketplaceOfferStartPolicy;
    'startTime'?: Date;
    'termDuration'?: GcpPeriodDuration;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enableScheduledStartTimes",
            "baseName": "enableScheduledStartTimes",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "startPolicy",
            "baseName": "startPolicy",
            "type": "GcpMarketplaceOfferStartPolicy",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "termDuration",
            "baseName": "termDuration",
            "type": "GcpPeriodDuration",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplacePrivateOfferTerm.attributeTypeMap;
    }

    public constructor() {
    }
}


