/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpMarketplaceMeteringMoney } from '../models/GcpMarketplaceMeteringMoney';
import { HttpFile } from '../http/http';

export class GcpMarketplaceMeteringMetricValue {
    /**
    * BoolValue: A boolean value.
    */
    'boolValue'?: boolean;
    /**
    * DoubleValue: A double precision floating point value.
    */
    'doubleValue'?: number;
    /**
    * EndTime: The end of the time period over which this metric value\'s measurement applies. If not specified, google.api.servicecontrol.v1.Operation.end_time will be used.
    */
    'endTime'?: string;
    /**
    * Int64Value: A signed 64-bit integer value.
    */
    'int64Value'?: string;
    /**
    * Labels: The labels describing the metric value. See comments on google.api.servicecontrol.v1.Operation.labels for the overriding relationship. Note that this map must not contain monitored resource labels.
    */
    'labels'?: { [key: string]: string; };
    /**
    * MoneyValue: A money value.
    */
    'moneyValue'?: GcpMarketplaceMeteringMoney;
    /**
    * StartTime: The start of the time period over which this metric value\'s measurement applies. The time period has different semantics for different metric types (cumulative, delta, and gauge). See the metric definition documentation in the service configuration for details. If not specified, google.api.servicecontrol.v1.Operation.start_time will be used.
    */
    'startTime'?: string;
    /**
    * StringValue: A text string value.
    */
    'stringValue'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "boolValue",
            "baseName": "boolValue",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "doubleValue",
            "baseName": "doubleValue",
            "type": "number",
            "format": ""
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "int64Value",
            "baseName": "int64Value",
            "type": "string",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "moneyValue",
            "baseName": "moneyValue",
            "type": "GcpMarketplaceMeteringMoney",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "stringValue",
            "baseName": "stringValue",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplaceMeteringMetricValue.attributeTypeMap;
    }

    public constructor() {
    }
}
