/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpMarketplaceResellerPrivateOfferPlanPriceModelSkuRepresentation } from '../models/GcpMarketplaceResellerPrivateOfferPlanPriceModelSkuRepresentation';
import { GcpPeriodDuration } from '../models/GcpPeriodDuration';
import { GcpPriceModelDiscountTemplate } from '../models/GcpPriceModelDiscountTemplate';
import { HttpFile } from '../http/http';

export class GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplatePayg {
    'discountTemplate'?: GcpPriceModelDiscountTemplate;
    'period'?: GcpPeriodDuration;
    'skuDiscountTemplates'?: Array<any>;
    'skuRepresentation'?: GcpMarketplaceResellerPrivateOfferPlanPriceModelSkuRepresentation;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "discountTemplate",
            "baseName": "discountTemplate",
            "type": "GcpPriceModelDiscountTemplate",
            "format": ""
        },
        {
            "name": "period",
            "baseName": "period",
            "type": "GcpPeriodDuration",
            "format": ""
        },
        {
            "name": "skuDiscountTemplates",
            "baseName": "skuDiscountTemplates",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "skuRepresentation",
            "baseName": "skuRepresentation",
            "type": "GcpMarketplaceResellerPrivateOfferPlanPriceModelSkuRepresentation",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplatePayg.attributeTypeMap;
    }

    public constructor() {
    }
}
