/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpMarketplaceProductFeature } from '../models/GcpMarketplaceProductFeature';
import { GcpMarketplaceProductMeteringMetric } from '../models/GcpMarketplaceProductMeteringMetric';
import { GcpMarketplaceProductPurchaseOptionSpec } from '../models/GcpMarketplaceProductPurchaseOptionSpec';
import { HttpFile } from '../http/http';

export class GcpMarketplaceProductPurchaseSpec {
    'features'?: Array<GcpMarketplaceProductFeature>;
    /**
    * GCP Marketplace Product Usage Metering Dimension/Metric
    */
    'metrics'?: Array<GcpMarketplaceProductMeteringMetric>;
    /**
    * GCP Marketplace Product Pricing Plans
    */
    'purchaseOptionSpecs'?: Array<GcpMarketplaceProductPurchaseOptionSpec>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "features",
            "baseName": "features",
            "type": "Array<GcpMarketplaceProductFeature>",
            "format": ""
        },
        {
            "name": "metrics",
            "baseName": "metrics",
            "type": "Array<GcpMarketplaceProductMeteringMetric>",
            "format": ""
        },
        {
            "name": "purchaseOptionSpecs",
            "baseName": "purchaseOptionSpecs",
            "type": "Array<GcpMarketplaceProductPurchaseOptionSpec>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplaceProductPurchaseSpec.attributeTypeMap;
    }

    public constructor() {
    }
}
