/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum GcpMarketplaceOfferDealType {
    GcpMarketplaceOfferDealTypeNew = 'OFFER_DEAL_TYPE_UNSPECIFIED',
    GcpMarketplaceOfferDealTypeChannelShift = 'CHANNEL_SHIFT',
    GcpMarketplaceOfferDealTypeMigration = 'MIGRATION',
    GcpMarketplaceOfferDealTypeNativeRenewal = 'NATIVE_RENEWAL'
}
