/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GcpMarketplacePrivateOfferProviderInfo {
    /**
    * The email address of who create the private offer in the provider.
    */
    'creatorEmailAddress'?: string;
    /**
    * The sales contact email of the provider.
    */
    'salesContactEmail'?: string;
    /**
    * The sales contact name of the provider.
    */
    'salesContactName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "creatorEmailAddress",
            "baseName": "creatorEmailAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "salesContactEmail",
            "baseName": "salesContactEmail",
            "type": "string",
            "format": ""
        },
        {
            "name": "salesContactName",
            "baseName": "salesContactName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplacePrivateOfferProviderInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
