/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpMarketplaceProductExternalAccountSpec } from '../models/GcpMarketplaceProductExternalAccountSpec';
import { GcpMarketplaceProductMarketingSpec } from '../models/GcpMarketplaceProductMarketingSpec';
import { GcpMarketplaceProductPurchaseSpec } from '../models/GcpMarketplaceProductPurchaseSpec';
import { GcpMarketplaceProductTermsSpec } from '../models/GcpMarketplaceProductTermsSpec';
import { HttpFile } from '../http/http';

export class GcpMarketplaceProductListingSpec {
    'externalAccountSpec'?: GcpMarketplaceProductExternalAccountSpec;
    'listingType'?: GcpMarketplaceProductListingSpecListingTypeEnum;
    'marketingSpec'?: GcpMarketplaceProductMarketingSpec;
    'purchaseSpec'?: GcpMarketplaceProductPurchaseSpec;
    'termsSpec'?: GcpMarketplaceProductTermsSpec;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "externalAccountSpec",
            "baseName": "externalAccountSpec",
            "type": "GcpMarketplaceProductExternalAccountSpec",
            "format": ""
        },
        {
            "name": "listingType",
            "baseName": "listingType",
            "type": "GcpMarketplaceProductListingSpecListingTypeEnum",
            "format": ""
        },
        {
            "name": "marketingSpec",
            "baseName": "marketingSpec",
            "type": "GcpMarketplaceProductMarketingSpec",
            "format": ""
        },
        {
            "name": "purchaseSpec",
            "baseName": "purchaseSpec",
            "type": "GcpMarketplaceProductPurchaseSpec",
            "format": ""
        },
        {
            "name": "termsSpec",
            "baseName": "termsSpec",
            "type": "GcpMarketplaceProductTermsSpec",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplaceProductListingSpec.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum GcpMarketplaceProductListingSpecListingTypeEnum {
    BillingIntegratedManagedService = 'BillingIntegratedManagedService'
}

