/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpPriceValue } from '../models/GcpPriceValue';
import { HttpFile } from '../http/http';

export class GcpMarketplaceProductSubscriptionPlan {
    /**
    * such as \"ONE_YEAR\", \"TWO_YEAR\", \"THREE_YEAR\"
    */
    'period'?: string;
    'price'?: GcpPriceValue;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "period",
            "baseName": "period",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "GcpPriceValue",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplaceProductSubscriptionPlan.attributeTypeMap;
    }

    public constructor() {
    }
}
