/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpMarketplaceRevenueShareChange } from '../models/GcpMarketplaceRevenueShareChange';
import { GcpMarketplaceRevenueShareValue } from '../models/GcpMarketplaceRevenueShareValue';
import { HttpFile } from '../http/http';

export class GcpMarketplacePrivateOfferRevenueShare {
    'autoRenewRevenueShare'?: GcpMarketplaceRevenueShareValue;
    'revenueShare'?: GcpMarketplaceRevenueShareValue;
    'revenueShareChanges'?: Array<GcpMarketplaceRevenueShareChange>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "autoRenewRevenueShare",
            "baseName": "autoRenewRevenueShare",
            "type": "GcpMarketplaceRevenueShareValue",
            "format": ""
        },
        {
            "name": "revenueShare",
            "baseName": "revenueShare",
            "type": "GcpMarketplaceRevenueShareValue",
            "format": ""
        },
        {
            "name": "revenueShareChanges",
            "baseName": "revenueShareChanges",
            "type": "Array<GcpMarketplaceRevenueShareChange>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplacePrivateOfferRevenueShare.attributeTypeMap;
    }

    public constructor() {
    }
}
