/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GcpMarketplaceResellerPrivateOfferPlanMetainfo {
    /**
    * Gcp Organiztion ID from integration with GCP Marketplace.
    */
    'gcpOrganizationId'?: string;
    /**
    * Gcp Project Number from integration with GCP Marketplace.
    */
    'gcpProjectNumber'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "gcpOrganizationId",
            "baseName": "gcpOrganizationId",
            "type": "string",
            "format": ""
        },
        {
            "name": "gcpProjectNumber",
            "baseName": "gcpProjectNumber",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplaceResellerPrivateOfferPlanMetainfo.attributeTypeMap;
    }

    public constructor() {
    }
}
