/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpMarketplaceDocument } from '../models/GcpMarketplaceDocument';
import { GcpMarketplacePrivateOfferInstallmentTimeline } from '../models/GcpMarketplacePrivateOfferInstallmentTimeline';
import { GcpMarketplacePrivateOfferPriceModel } from '../models/GcpMarketplacePrivateOfferPriceModel';
import { GcpMarketplacePrivateOfferTerm } from '../models/GcpMarketplacePrivateOfferTerm';
import { PaymentScheduleType } from '../models/PaymentScheduleType';
import { HttpFile } from '../http/http';

export class GcpMarketplaceExistingPrivateOffer {
    'agreement'?: string;
    'customEula'?: GcpMarketplaceDocument;
    'installmentTimeline'?: GcpMarketplacePrivateOfferInstallmentTimeline;
    /**
    * GCP private offer resource name.
    */
    'name'?: string;
    'offerTerm'?: GcpMarketplacePrivateOfferTerm;
    'paymentSchedule'?: PaymentScheduleType;
    /**
    * Nill if the offer has payment installments.
    */
    'priceModel'?: GcpMarketplacePrivateOfferPriceModel;
    /**
    * The Plan of the offer.
    */
    'serviceLevel'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "agreement",
            "baseName": "agreement",
            "type": "string",
            "format": ""
        },
        {
            "name": "customEula",
            "baseName": "customEula",
            "type": "GcpMarketplaceDocument",
            "format": ""
        },
        {
            "name": "installmentTimeline",
            "baseName": "installmentTimeline",
            "type": "GcpMarketplacePrivateOfferInstallmentTimeline",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "offerTerm",
            "baseName": "offerTerm",
            "type": "GcpMarketplacePrivateOfferTerm",
            "format": ""
        },
        {
            "name": "paymentSchedule",
            "baseName": "paymentSchedule",
            "type": "PaymentScheduleType",
            "format": ""
        },
        {
            "name": "priceModel",
            "baseName": "priceModel",
            "type": "GcpMarketplacePrivateOfferPriceModel",
            "format": ""
        },
        {
            "name": "serviceLevel",
            "baseName": "serviceLevel",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpMarketplaceExistingPrivateOffer.attributeTypeMap;
    }

    public constructor() {
    }
}


