/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GcpPeriodDurationUnit } from '../models/GcpPeriodDurationUnit';
import { HttpFile } from '../http/http';

export class GcpPeriodDuration {
    /**
    * such as 1, 6, 12
    */
    'count'?: number;
    'unit'?: GcpPeriodDurationUnit;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "GcpPeriodDurationUnit",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GcpPeriodDuration.attributeTypeMap;
    }

    public constructor() {
    }
}


