/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RevenueReportType } from '../models/RevenueReportType';
import { HttpFile } from '../http/http';

export class GetRevenueReportParams {
    /**
    * Optional, if available, return the report for the Buyer.
    */
    'buyerID'?: string;
    /**
    * Optional, if available, return the report for the Entitlement.
    */
    'entitlementID'?: string;
    /**
    * Required. If the productID & entitlementID are emtpy, return the report for the entire Organization.
    */
    'organizationID': string;
    'partner': GetRevenueReportParamsPartnerEnum;
    /**
    * Optional, if available, return the report for the Product.
    */
    'productID'?: string;
    'reportType': RevenueReportType;
    'service': GetRevenueReportParamsServiceEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "buyerID",
            "baseName": "buyerID",
            "type": "string",
            "format": ""
        },
        {
            "name": "entitlementID",
            "baseName": "entitlementID",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationID",
            "baseName": "organizationID",
            "type": "string",
            "format": ""
        },
        {
            "name": "partner",
            "baseName": "partner",
            "type": "GetRevenueReportParamsPartnerEnum",
            "format": ""
        },
        {
            "name": "productID",
            "baseName": "productID",
            "type": "string",
            "format": ""
        },
        {
            "name": "reportType",
            "baseName": "reportType",
            "type": "RevenueReportType",
            "format": ""
        },
        {
            "name": "service",
            "baseName": "service",
            "type": "GetRevenueReportParamsServiceEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetRevenueReportParams.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum GetRevenueReportParamsPartnerEnum {
    Aws = 'AWS',
    Azure = 'AZURE',
    Gcp = 'GCP'
}
export enum GetRevenueReportParamsServiceEnum {
    Marketplace = 'MARKETPLACE'
}

