/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingGcpChargeUsage {
    'abandoned'?: number;
    'accountID'?: string;
    'buyerID'?: string;
    'charges'?: number;
    'currency'?: string;
    'dueVendor'?: number;
    'entitlementID'?: string;
    'googleEntity'?: string;
    'insightAccountID'?: string;
    'offerID'?: string;
    'ordinal'?: number;
    'organizationID'?: string;
    'paymentSchedule'?: string;
    'paymentType'?: string;
    'prepayCredits'?: number;
    'productID'?: string;
    'refundBalanceDeductedThisMonth'?: number;
    'refundBalanceOutstanding'?: number;
    'refundReason'?: string;
    'released'?: number;
    'reportDate'?: string;
    'resource'?: string;
    'sku'?: string;
    'trialUse'?: number;
    'unit'?: string;
    'usage'?: number;
    'usedBy'?: string;
    'withheld'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "abandoned",
            "baseName": "abandoned",
            "type": "number",
            "format": ""
        },
        {
            "name": "accountID",
            "baseName": "accountID",
            "type": "string",
            "format": ""
        },
        {
            "name": "buyerID",
            "baseName": "buyerID",
            "type": "string",
            "format": ""
        },
        {
            "name": "charges",
            "baseName": "charges",
            "type": "number",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "dueVendor",
            "baseName": "dueVendor",
            "type": "number",
            "format": ""
        },
        {
            "name": "entitlementID",
            "baseName": "entitlementID",
            "type": "string",
            "format": ""
        },
        {
            "name": "googleEntity",
            "baseName": "googleEntity",
            "type": "string",
            "format": ""
        },
        {
            "name": "insightAccountID",
            "baseName": "insightAccountID",
            "type": "string",
            "format": ""
        },
        {
            "name": "offerID",
            "baseName": "offerID",
            "type": "string",
            "format": ""
        },
        {
            "name": "ordinal",
            "baseName": "ordinal",
            "type": "number",
            "format": ""
        },
        {
            "name": "organizationID",
            "baseName": "organizationID",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentSchedule",
            "baseName": "paymentSchedule",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentType",
            "baseName": "paymentType",
            "type": "string",
            "format": ""
        },
        {
            "name": "prepayCredits",
            "baseName": "prepayCredits",
            "type": "number",
            "format": ""
        },
        {
            "name": "productID",
            "baseName": "productID",
            "type": "string",
            "format": ""
        },
        {
            "name": "refundBalanceDeductedThisMonth",
            "baseName": "refundBalanceDeductedThisMonth",
            "type": "number",
            "format": ""
        },
        {
            "name": "refundBalanceOutstanding",
            "baseName": "refundBalanceOutstanding",
            "type": "number",
            "format": ""
        },
        {
            "name": "refundReason",
            "baseName": "refundReason",
            "type": "string",
            "format": ""
        },
        {
            "name": "released",
            "baseName": "released",
            "type": "number",
            "format": ""
        },
        {
            "name": "reportDate",
            "baseName": "reportDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "resource",
            "baseName": "resource",
            "type": "string",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "trialUse",
            "baseName": "trialUse",
            "type": "number",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "usage",
            "baseName": "usage",
            "type": "number",
            "format": ""
        },
        {
            "name": "usedBy",
            "baseName": "usedBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "withheld",
            "baseName": "withheld",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingGcpChargeUsage.attributeTypeMap;
    }

    public constructor() {
    }
}
