/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GithubComAwsAwsSdkGoV2ServiceMarketplacemeteringTypesTag {
    /**
    * One part of a key-value pair that makes up a tag . A key is a label that acts like a category for the specific tag values.  This member is required.
    */
    'key'?: string;
    /**
    * One part of a key-value pair that makes up a tag . A value acts as a descriptor within a tag category (key). The value can be empty or null.  This member is required.
    */
    'value'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GithubComAwsAwsSdkGoV2ServiceMarketplacemeteringTypesTag.attributeTypeMap;
    }

    public constructor() {
    }
}
