/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeteringUsageRecordGroup } from '../models/MeteringUsageRecordGroup';
import { HttpFile } from '../http/http';

export class ListUsageRecordGroupsResponse {
    'nextOffset'?: number;
    'usageRecordGroups'?: Array<MeteringUsageRecordGroup>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nextOffset",
            "baseName": "nextOffset",
            "type": "number",
            "format": ""
        },
        {
            "name": "usageRecordGroups",
            "baseName": "usageRecordGroups",
            "type": "Array<MeteringUsageRecordGroup>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListUsageRecordGroupsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
