/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NotificationMessage } from '../models/NotificationMessage';
import { HttpFile } from '../http/http';

export class ListNotificationMessagesResponse {
    /**
    * The next offset to use in the next request to get the next page of notification messages. If this field is null, there are no more notification messages to get.
    */
    'nextOffset'?: number;
    'notificationMessages'?: Array<NotificationMessage>;
    /**
    * The total number of notification messages. Only available when the request is made with the first offset = 0.
    */
    'totalCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nextOffset",
            "baseName": "nextOffset",
            "type": "number",
            "format": ""
        },
        {
            "name": "notificationMessages",
            "baseName": "notificationMessages",
            "type": "Array<NotificationMessage>",
            "format": ""
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListNotificationMessagesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
