/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NotificationChannel } from '../models/NotificationChannel';
import { NotificationMessageInfo } from '../models/NotificationMessageInfo';
import { HttpFile } from '../http/http';

export class NotificationMessage {
    'creationTime'?: Date;
    'id'?: string;
    'info'?: NotificationMessageInfo;
    'organizationID'?: string;
    'recipient'?: string;
    'type'?: NotificationChannel;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "creationTime",
            "baseName": "creationTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "info",
            "baseName": "info",
            "type": "NotificationMessageInfo",
            "format": ""
        },
        {
            "name": "organizationID",
            "baseName": "organizationID",
            "type": "string",
            "format": ""
        },
        {
            "name": "recipient",
            "baseName": "recipient",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "NotificationChannel",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NotificationMessage.attributeTypeMap;
    }

    public constructor() {
    }
}


