/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NotificationEventAction } from '../models/NotificationEventAction';
import { HttpFile } from '../http/http';

export class NotificationMessageInfo {
    /**
    * The action of this notification message.
    */
    'action'?: NotificationEventAction;
    'ccRecipients'?: Array<string>;
    /**
    * All other fields
    */
    'customFields'?: { [key: string]: any; };
    /**
    * The HTML content of the email.
    */
    'htmlContent'?: string;
    'rccRecipients'?: Array<string>;
    /**
    * The standard fields to render the email content.
    */
    'standardFields'?: { [key: string]: any; };
    'subject'?: string;
    /**
    * The text content of the email in case the recipient\'s email client does not support HTML.
    */
    'textContent'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "NotificationEventAction",
            "format": ""
        },
        {
            "name": "ccRecipients",
            "baseName": "ccRecipients",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "customFields",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "htmlContent",
            "baseName": "htmlContent",
            "type": "string",
            "format": ""
        },
        {
            "name": "rccRecipients",
            "baseName": "rccRecipients",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "standardFields",
            "baseName": "standardFields",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string",
            "format": ""
        },
        {
            "name": "textContent",
            "baseName": "textContent",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NotificationMessageInfo.attributeTypeMap;
    }

    public constructor() {
    }
}


