/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum NotificationChannel {
    NotificationChannel_EMAIL = 'EMAIL',
    NotificationChannel_SLACK = 'SLACK',
    NotificationChannel_SMS = 'SMS',
    NotificationChannel_SNS = 'SNS',
    NotificationChannel_SALESFORCE = 'SALESFORCE',
    NotificationChannel_WEBHOOK = 'WEBHOOK',
    NotificationChannel_SUGER_SUPPORT = 'SUGER_SUPPORT',
    NotificationChannel_MICROSOFT_TEAMS = 'MICROSOFT_TEAMS'
}
