/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum OfferType {
    OfferType_UNKNOWN = 'UNKNOWN',
    OfferType_AMI = 'AMI',
    OfferType_CONTAINER = 'CONTAINER',
    OfferType_CONTRACT = 'CONTRACT',
    OfferType_CPPO_OUT = 'CPPO_OUT',
    OfferType_CPPO_IN = 'CPPO_IN',
    OfferType_CPPO = 'CPPO',
    OfferType_CUD = 'CUD',
    OfferType_DEFAULT = 'DEFAULT',
    OfferType_FIXED_FEE = 'FIXED_FEE',
    OfferType_FIXED_FEE_WITH_OVERAGE = 'FIXED_FEE_WITH_OVERAGE',
    OfferType_FLAT_RATE = 'FLAT_RATE',
    OfferType_FREE_TRIAL = 'FREE_TRIAL',
    OfferType_PAYG = 'PAYG',
    OfferType_PAYG_WITH_CUD = 'PAYG_WITH_CUD',
    OfferType_PER_USER = 'PER_USER',
    OfferType_PRIVATE = 'PRIVATE',
    OfferType_PROFESSIONAL_SERVICES = 'PROFESSIONAL_SERVICES',
    OfferType_SUBSCRIPTION = 'SUBSCRIPTION'
}
