/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum PartnerService {
    PartnerService_DEFAULT = 'DEFAULT',
    PartnerService_ACE = 'ACE',
    PartnerService_BIGQUERY = 'BIGQUERY',
    PartnerService_BILLING = 'BILLING',
    PartnerService_CHATBOT = 'CHATBOT',
    PartnerService_COSELL = 'COSELL',
    PartnerService_CRM = 'CRM',
    PartnerService_CPQ = 'CPQ',
    PartnerService_DATABASE = 'DATABASE',
    PartnerService_DRIVE = 'DRIVE',
    PartnerService_EMAIL = 'EMAIL',
    PartnerService_MARKETPLACE = 'MARKETPLACE',
    PartnerService_NETSUITE = 'NETSUITE',
    PartnerService_PAYMENT = 'PAYMENT',
    PartnerService_QUICKBOOKS = 'QUICKBOOKS',
    PartnerService_STORAGE = 'STORAGE',
    PartnerService_TEAMS = 'TEAMS'
}
