/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BillingWalletType } from '../models/BillingWalletType';
import { HttpFile } from '../http/http';

export class PaymentConfig {
    /**
    * Allowed wallet types for this buyer, include payment methods from payment provider such as card, us_bank_account and credit.
    */
    'allowedWalletTypes'?: Array<BillingWalletType>;
    /**
    * Currency used for billing.
    */
    'currency'?: string;
    /**
    * Default wallet id which is a stripe payment method used to invoice.
    */
    'defaultWalletId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "allowedWalletTypes",
            "baseName": "allowedWalletTypes",
            "type": "Array<BillingWalletType>",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultWalletId",
            "baseName": "defaultWalletId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentConfig.attributeTypeMap;
    }

    public constructor() {
    }
}
