/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PaymentInstallment {
    /**
    * The amount the buyer has paid for this installment. If there is a discount off the original price, the amount is the discounted price.
    */
    'amount'?: number;
    /**
    * When the buyer will be charged for this installment. If it is null, the buyer will be charged on the effective date of the entitlement.
    */
    'chargeOn'?: Date;
    /**
    * The charge on date in string format. It is used for front-end display only.
    */
    'chargeOnStr'?: string;
    /**
    * Used in GCP Marketplace private offer as one-time credit. Default as zero if there is no credit.
    */
    'credit'?: number;
    /**
    * The discount percentage off the original price. For GCP Marketplace, it can be discount off the commitment amount or discount off the usage price. The value is between 0 to 100. For example, 20 means 20% off. Default as zero if there is no discount.
    */
    'discountPercentage'?: number;
    /**
    * The original amount before discount if there is a discount off the original price. nil if there is no discount.
    */
    'originalAmount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "chargeOn",
            "baseName": "chargeOn",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "chargeOnStr",
            "baseName": "chargeOnStr",
            "type": "string",
            "format": ""
        },
        {
            "name": "credit",
            "baseName": "credit",
            "type": "number",
            "format": ""
        },
        {
            "name": "discountPercentage",
            "baseName": "discountPercentage",
            "type": "number",
            "format": ""
        },
        {
            "name": "originalAmount",
            "baseName": "originalAmount",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentInstallment.attributeTypeMap;
    }

    public constructor() {
    }
}
