/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PriceModelTieredPercentageConfig {
    /**
    * Inclusive tier starting value
    */
    'firstUnit'?: number;
    'flatFee'?: number;
    /**
    * Exclusive tier ending value. If null, this is treated as the last tier
    */
    'lastUnit'?: number;
    'percentageRate'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "firstUnit",
            "baseName": "firstUnit",
            "type": "number",
            "format": ""
        },
        {
            "name": "flatFee",
            "baseName": "flatFee",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastUnit",
            "baseName": "lastUnit",
            "type": "number",
            "format": ""
        },
        {
            "name": "percentageRate",
            "baseName": "percentageRate",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PriceModelTieredPercentageConfig.attributeTypeMap;
    }

    public constructor() {
    }
}
