/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PriceModelMatrixConfigGroup } from '../models/PriceModelMatrixConfigGroup';
import { HttpFile } from '../http/http';

export class PriceModelMatrix {
    'defaultUnitAmount'?: number;
    /**
    * The matrix of the pricing model
    */
    'matrix'?: Array<PriceModelMatrixConfigGroup>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "defaultUnitAmount",
            "baseName": "defaultUnitAmount",
            "type": "number",
            "format": ""
        },
        {
            "name": "matrix",
            "baseName": "matrix",
            "type": "Array<PriceModelMatrixConfigGroup>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PriceModelMatrix.attributeTypeMap;
    }

    public constructor() {
    }
}
