/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlibabaMarketplaceProduct } from '../models/AlibabaMarketplaceProduct';
import { AwsProduct } from '../models/AwsProduct';
import { AwsSnsSubscription } from '../models/AwsSnsSubscription';
import { AzureMarketplaceProductResource } from '../models/AzureMarketplaceProductResource';
import { AzureProduct } from '../models/AzureProduct';
import { CommitDimension } from '../models/CommitDimension';
import { EulaType } from '../models/EulaType';
import { GcpMarketplaceProduct } from '../models/GcpMarketplaceProduct';
import { MeteringDimension } from '../models/MeteringDimension';
import { StripeProduct } from '../models/StripeProduct';
import { HttpFile } from '../http/http';

export class ProductInfo {
    'alibabaProduct'?: AlibabaMarketplaceProduct;
    'attributes'?: { [key: string]: string; };
    'awsAmiProduct'?: AwsProduct;
    'awsContainerProduct'?: AwsProduct;
    'awsProfessionalServicesProduct'?: AwsProduct;
    'awsSaasProduct'?: AwsProduct;
    'awsSnsSubscriptions'?: Array<AwsSnsSubscription>;
    'azureProduct'?: AzureProduct;
    'azureProductResource'?: AzureMarketplaceProductResource;
    'commits'?: Array<CommitDimension>;
    'currency'?: string;
    'dimensions'?: Array<MeteringDimension>;
    /**
    * The public offer\'s EULA type.
    */
    'eulaType'?: EulaType;
    /**
    * The public offer\'s EULA URL.
    */
    'eulaUrl'?: string;
    'gcpProduct'?: GcpMarketplaceProduct;
    'refundCancellationPolicy'?: string;
    'sellerNotes'?: string;
    'stripeProduct'?: StripeProduct;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "alibabaProduct",
            "baseName": "alibabaProduct",
            "type": "AlibabaMarketplaceProduct",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "awsAmiProduct",
            "baseName": "awsAmiProduct",
            "type": "AwsProduct",
            "format": ""
        },
        {
            "name": "awsContainerProduct",
            "baseName": "awsContainerProduct",
            "type": "AwsProduct",
            "format": ""
        },
        {
            "name": "awsProfessionalServicesProduct",
            "baseName": "awsProfessionalServicesProduct",
            "type": "AwsProduct",
            "format": ""
        },
        {
            "name": "awsSaasProduct",
            "baseName": "awsSaasProduct",
            "type": "AwsProduct",
            "format": ""
        },
        {
            "name": "awsSnsSubscriptions",
            "baseName": "awsSnsSubscriptions",
            "type": "Array<AwsSnsSubscription>",
            "format": ""
        },
        {
            "name": "azureProduct",
            "baseName": "azureProduct",
            "type": "AzureProduct",
            "format": ""
        },
        {
            "name": "azureProductResource",
            "baseName": "azureProductResource",
            "type": "AzureMarketplaceProductResource",
            "format": ""
        },
        {
            "name": "commits",
            "baseName": "commits",
            "type": "Array<CommitDimension>",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "dimensions",
            "baseName": "dimensions",
            "type": "Array<MeteringDimension>",
            "format": ""
        },
        {
            "name": "eulaType",
            "baseName": "eulaType",
            "type": "EulaType",
            "format": ""
        },
        {
            "name": "eulaUrl",
            "baseName": "eulaUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "gcpProduct",
            "baseName": "gcpProduct",
            "type": "GcpMarketplaceProduct",
            "format": ""
        },
        {
            "name": "refundCancellationPolicy",
            "baseName": "refundCancellationPolicy",
            "type": "string",
            "format": ""
        },
        {
            "name": "sellerNotes",
            "baseName": "sellerNotes",
            "type": "string",
            "format": ""
        },
        {
            "name": "stripeProduct",
            "baseName": "stripeProduct",
            "type": "StripeProduct",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductInfo.attributeTypeMap;
    }

    public constructor() {
    }
}


