/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GithubComSugerioMarketplaceServiceRdsDbLibBillingAwsBillingEvent } from '../models/GithubComSugerioMarketplaceServiceRdsDbLibBillingAwsBillingEvent';
import { GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue } from '../models/GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue';
import { GithubComSugerioMarketplaceServiceRdsDbLibBillingGcpChargeUsage } from '../models/GithubComSugerioMarketplaceServiceRdsDbLibBillingGcpChargeUsage';
import { HttpFile } from '../http/http';

export class RevenueRecordDetail {
    /**
    * For AWS Marketplace
    */
    'awsRevenueRecordDetail'?: GithubComSugerioMarketplaceServiceRdsDbLibBillingAwsBillingEvent;
    /**
    * For Azure Marketplace
    */
    'azureRevenueRecordDetail'?: GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue;
    /**
    * For GCP Marketplace
    */
    'gcpRevenueRecordDetail'?: GithubComSugerioMarketplaceServiceRdsDbLibBillingGcpChargeUsage;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "awsRevenueRecordDetail",
            "baseName": "awsRevenueRecordDetail",
            "type": "GithubComSugerioMarketplaceServiceRdsDbLibBillingAwsBillingEvent",
            "format": ""
        },
        {
            "name": "azureRevenueRecordDetail",
            "baseName": "azureRevenueRecordDetail",
            "type": "GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue",
            "format": ""
        },
        {
            "name": "gcpRevenueRecordDetail",
            "baseName": "gcpRevenueRecordDetail",
            "type": "GithubComSugerioMarketplaceServiceRdsDbLibBillingGcpChargeUsage",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RevenueRecordDetail.attributeTypeMap;
    }

    public constructor() {
    }
}
