/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingAwsBillingEvent } from '../models/GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingAwsBillingEvent';
import { GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingAzureCmaRevenue } from '../models/GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingAzureCmaRevenue';
import { GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingGcpChargeUsage } from '../models/GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingGcpChargeUsage';
import { HttpFile } from '../http/http';

export class RevenueRecordInfo {
    /**
    * For raw revenue records in AWS Marketplace
    */
    'awsRevenueRecords'?: Array<GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingAwsBillingEvent>;
    /**
    * For raw revenue records in Azure Marketplace
    */
    'azureRevenueRecords'?: Array<GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingAzureCmaRevenue>;
    /**
    * The credit amount used in the revenue record.
    */
    'creditAmount'?: number;
    /**
    * Whether the disbursement notification has been sent to the seller/ISV.
    */
    'disbursementNotificationSent'?: boolean;
    /**
    * For raw revenue records in GCP Marketplace
    */
    'gcpRevenueRecords'?: Array<GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingGcpChargeUsage>;
    /**
    * Source of the revenue record ID.
    */
    'idSource'?: string;
    /**
    * Resource name for the revenue record. Applicable only to GCP Marketplace.
    */
    'resource'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "awsRevenueRecords",
            "baseName": "awsRevenueRecords",
            "type": "Array<GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingAwsBillingEvent>",
            "format": ""
        },
        {
            "name": "azureRevenueRecords",
            "baseName": "azureRevenueRecords",
            "type": "Array<GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingAzureCmaRevenue>",
            "format": ""
        },
        {
            "name": "creditAmount",
            "baseName": "creditAmount",
            "type": "number",
            "format": ""
        },
        {
            "name": "disbursementNotificationSent",
            "baseName": "disbursementNotificationSent",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "gcpRevenueRecords",
            "baseName": "gcpRevenueRecords",
            "type": "Array<GithubComSugerioMarketplaceServicePkgLegacyRdsDbLibBillingGcpChargeUsage>",
            "format": ""
        },
        {
            "name": "idSource",
            "baseName": "idSource",
            "type": "string",
            "format": ""
        },
        {
            "name": "resource",
            "baseName": "resource",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RevenueRecordInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
