/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SnowflakeMarketplacePricingPlanUsageDetails {
    'freeUnitKind'?: string;
    'freeUnits'?: number;
    'maxFee'?: number;
    'usageUnitKind'?: string;
    'usageUnitPrice'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "freeUnitKind",
            "baseName": "free_unit_kind",
            "type": "string",
            "format": ""
        },
        {
            "name": "freeUnits",
            "baseName": "free_units",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxFee",
            "baseName": "max_fee",
            "type": "number",
            "format": ""
        },
        {
            "name": "usageUnitKind",
            "baseName": "usage_unit_kind",
            "type": "string",
            "format": ""
        },
        {
            "name": "usageUnitPrice",
            "baseName": "usage_unit_price",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SnowflakeMarketplacePricingPlanUsageDetails.attributeTypeMap;
    }

    public constructor() {
    }
}
