/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SnowflakeMarketplaceProductMetadata {
    'areTermsProvidedOffline'?: boolean;
    'businessNeeds'?: any;
    'description'?: string;
    'hasFreeSampleData'?: boolean;
    'isWithStandardTerms'?: boolean;
    'paidAttributes'?: any;
    'share'?: string;
    'title'?: string;
    'usage'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "areTermsProvidedOffline",
            "baseName": "areTermsProvidedOffline",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "businessNeeds",
            "baseName": "businessNeeds",
            "type": "any",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasFreeSampleData",
            "baseName": "hasFreeSampleData",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isWithStandardTerms",
            "baseName": "isWithStandardTerms",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "paidAttributes",
            "baseName": "paidAttributes",
            "type": "any",
            "format": ""
        },
        {
            "name": "share",
            "baseName": "share",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "usage",
            "baseName": "usage",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SnowflakeMarketplaceProductMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}
