/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SnowflakeMarketplacePricingPlanUsageDetails } from '../models/SnowflakeMarketplacePricingPlanUsageDetails';
import { HttpFile } from '../http/http';

export class SnowflakeMarketplaceProductPricingPlan {
    'baseFee'?: number;
    'billingDurationMonths'?: string;
    'comment'?: string;
    'contractDurationMonths'?: string;
    /**
    * PAY_AS_YOU_GO, LIMITED_TIME
    */
    'contractType'?: string;
    'currency'?: string;
    'displayName'?: string;
    /**
    * For pricing display purpose. eg: {\"price\":\"10\",\"button_text\":\"starter plan\"}
    */
    'metadata'?: { [key: string]: string; };
    'name'?: string;
    /**
    * pricing model: USAGE_BASED, FLAT_FEE
    */
    'pricingModel'?: string;
    /**
    * SELF_SERVE, PROACTIVE
    */
    'salesMotion'?: string;
    /**
    * state of pricing plan
    */
    'state'?: string;
    'updatedOn'?: string;
    'usageDetails'?: SnowflakeMarketplacePricingPlanUsageDetails;
    'visibility'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "baseFee",
            "baseName": "base_fee",
            "type": "number",
            "format": ""
        },
        {
            "name": "billingDurationMonths",
            "baseName": "billing_duration_months",
            "type": "string",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractDurationMonths",
            "baseName": "contract_duration_months",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractType",
            "baseName": "contract_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "pricingModel",
            "baseName": "pricing_model",
            "type": "string",
            "format": ""
        },
        {
            "name": "salesMotion",
            "baseName": "sales_motion",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedOn",
            "baseName": "updated_on",
            "type": "string",
            "format": ""
        },
        {
            "name": "usageDetails",
            "baseName": "usage_details",
            "type": "SnowflakeMarketplacePricingPlanUsageDetails",
            "format": ""
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SnowflakeMarketplaceProductPricingPlan.attributeTypeMap;
    }

    public constructor() {
    }
}
