/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SnowflakeMarketplaceTrialDetails {
    'description'?: string;
    'trialTimeLimit'?: number;
    'trialType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "trialTimeLimit",
            "baseName": "trial_time_limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "trialType",
            "baseName": "trial_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SnowflakeMarketplaceTrialDetails.attributeTypeMap;
    }

    public constructor() {
    }
}
