/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StripePaymentMethodUSBankAccount {
    /**
    * Account holder type: individual or company.
    */
    'accountHolderType'?: StripePaymentMethodUSBankAccountAccountHolderTypeEnum;
    /**
    * Account type: checkings or savings. Defaults to checking if omitted.
    */
    'accountType'?: StripePaymentMethodUSBankAccountAccountTypeEnum;
    /**
    * The name of the bank.
    */
    'bankName'?: string;
    /**
    * Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same.
    */
    'fingerprint'?: string;
    /**
    * Last four digits of the bank account number.
    */
    'last4'?: string;
    /**
    * Routing number of the bank account.
    */
    'routingNumber'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accountHolderType",
            "baseName": "account_holder_type",
            "type": "StripePaymentMethodUSBankAccountAccountHolderTypeEnum",
            "format": ""
        },
        {
            "name": "accountType",
            "baseName": "account_type",
            "type": "StripePaymentMethodUSBankAccountAccountTypeEnum",
            "format": ""
        },
        {
            "name": "bankName",
            "baseName": "bank_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "string",
            "format": ""
        },
        {
            "name": "last4",
            "baseName": "last4",
            "type": "string",
            "format": ""
        },
        {
            "name": "routingNumber",
            "baseName": "routing_number",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StripePaymentMethodUSBankAccount.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum StripePaymentMethodUSBankAccountAccountHolderTypeEnum {
    Individual = 'individual',
    Company = 'company'
}
export enum StripePaymentMethodUSBankAccountAccountTypeEnum {
    Checking = 'checking',
    Savings = 'savings'
}

