/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StripeError } from '../models/StripeError';
import { StripePaymentIntentStatus } from '../models/StripePaymentIntentStatus';
import { HttpFile } from '../http/http';

export class StripePaymentIntent {
    /**
    * Unique identifier for the object.
    */
    'id'?: string;
    /**
    * The payment error encountered in the previous PaymentIntent confirmation. It will be cleared if the PaymentIntent is later updated for any reason.
    */
    'lastPaymentError'?: StripeError;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode'?: boolean;
    /**
    * Status of this PaymentIntent. Read more about each PaymentIntent [status](https://stripe.com/docs/payments/intents#intent-statuses).
    */
    'status'?: StripePaymentIntentStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastPaymentError",
            "baseName": "last_payment_error",
            "type": "StripeError",
            "format": ""
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "StripePaymentIntentStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StripePaymentIntent.attributeTypeMap;
    }

    public constructor() {
    }
}


