/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StripePaymentMethodBACSDebit } from '../models/StripePaymentMethodBACSDebit';
import { StripePaymentMethodCard } from '../models/StripePaymentMethodCard';
import { StripePaymentMethodSEPADebit } from '../models/StripePaymentMethodSEPADebit';
import { StripePaymentMethodUSBankAccount } from '../models/StripePaymentMethodUSBankAccount';
import { HttpFile } from '../http/http';

export class StripePaymentMethod {
    'bacsDebit'?: StripePaymentMethodBACSDebit;
    'card'?: StripePaymentMethodCard;
    /**
    * Time at which the object was created. Measured in seconds since the Unix epoch.
    */
    'created'?: number;
    /**
    * Unique identifier for the payment method on stripe.
    */
    'id'?: string;
    /**
    * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    */
    'livemode'?: boolean;
    /**
    * String representing the object’s type. Always has the value `payment_method`.
    */
    'object'?: string;
    'sepaDebit'?: StripePaymentMethodSEPADebit;
    'usBankAccount'?: StripePaymentMethodUSBankAccount;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bacsDebit",
            "baseName": "bacs_debit",
            "type": "StripePaymentMethodBACSDebit",
            "format": ""
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "StripePaymentMethodCard",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "sepaDebit",
            "baseName": "sepa_debit",
            "type": "StripePaymentMethodSEPADebit",
            "format": ""
        },
        {
            "name": "usBankAccount",
            "baseName": "us_bank_account",
            "type": "StripePaymentMethodUSBankAccount",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StripePaymentMethod.attributeTypeMap;
    }

    public constructor() {
    }
}
