/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StripeRefundDestinationDetailsCard {
    /**
    * Value of the reference number assigned to the refund.
    */
    'reference'?: string;
    /**
    * Status of the reference number on the refund. This can be `pending`, `available` or `unavailable`.
    */
    'referenceStatus'?: StripeRefundDestinationDetailsCardReferenceStatusEnum;
    /**
    * Type of the reference number assigned to the refund.
    */
    'referenceType'?: string;
    /**
    * The type of refund. This can be `refund`, `reversal`, or `pending`.
    */
    'type'?: StripeRefundDestinationDetailsCardTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "referenceStatus",
            "baseName": "reference_status",
            "type": "StripeRefundDestinationDetailsCardReferenceStatusEnum",
            "format": ""
        },
        {
            "name": "referenceType",
            "baseName": "reference_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "StripeRefundDestinationDetailsCardTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StripeRefundDestinationDetailsCard.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum StripeRefundDestinationDetailsCardReferenceStatusEnum {
    Pending = 'pending',
    Available = 'available',
    Unavailable = 'unavailable'
}
export enum StripeRefundDestinationDetailsCardTypeEnum {
    Refund = 'refund',
    Reversal = 'reversal',
    Pending = 'pending'
}

