/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StripePaymentMethodSEPADebit {
    /**
    * Bank code of bank associated with the bank account.
    */
    'bankCode'?: string;
    /**
    * Branch code of bank associated with the bank account.
    */
    'branchCode'?: string;
    /**
    * Two-letter ISO code representing the country the bank account is located in.
    */
    'country'?: string;
    /**
    * Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same.
    */
    'fingerprint'?: string;
    /**
    * Last four characters of the IBAN.
    */
    'last4'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bankCode",
            "baseName": "bank_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "branchCode",
            "baseName": "branch_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string",
            "format": ""
        },
        {
            "name": "fingerprint",
            "baseName": "fingerprint",
            "type": "string",
            "format": ""
        },
        {
            "name": "last4",
            "baseName": "last4",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StripePaymentMethodSEPADebit.attributeTypeMap;
    }

    public constructor() {
    }
}
