/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum StripePaymentIntentStatus {
    StripePaymentIntentStatus_RequiresPaymentMethod = 'requires_payment_method',
    StripePaymentIntentStatus_RequiresConfirmation = 'requires_confirmation',
    StripePaymentIntentStatus_RequiresAction = 'requires_action',
    StripePaymentIntentStatus_Processing = 'processing',
    StripePaymentIntentStatus_RequiresCapture = 'requires_capture',
    StripePaymentIntentStatus_Canceled = 'canceled',
    StripePaymentIntentStatus_Succeeded = 'succeeded'
}
