/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StripeRefundDestinationDetailsCard } from '../models/StripeRefundDestinationDetailsCard';
import { StripeRefundDestinationDetailsUSBankTransfer } from '../models/StripeRefundDestinationDetailsUSBankTransfer';
import { HttpFile } from '../http/http';

export class StripeRefundDestinationDetails {
    'card'?: StripeRefundDestinationDetailsCard;
    /**
    * The type of transaction-specific details of the payment method used in the refund (e.g., `card`). An additional hash is included on `destination_details` with a name matching this value. It contains information specific to the refund transaction.
    */
    'type'?: string;
    'usBankTransfer'?: StripeRefundDestinationDetailsUSBankTransfer;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "card",
            "baseName": "card",
            "type": "StripeRefundDestinationDetailsCard",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "usBankTransfer",
            "baseName": "us_bank_transfer",
            "type": "StripeRefundDestinationDetailsUSBankTransfer",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StripeRefundDestinationDetails.attributeTypeMap;
    }

    public constructor() {
    }
}
