/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SupportTicketUser {
    'email'?: string;
    /**
    * The Suger user ID.
    */
    'id'?: string;
    /**
    * Whether the user is a Suger employee.
    */
    'isSugerEmployee'?: boolean;
    'profilePicture'?: string;
    'username'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isSugerEmployee",
            "baseName": "isSugerEmployee",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "profilePicture",
            "baseName": "profilePicture",
            "type": "string",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupportTicketUser.attributeTypeMap;
    }

    public constructor() {
    }
}
