/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupportTicketAttachment } from '../models/SupportTicketAttachment';
import { SupportTicketFrame } from '../models/SupportTicketFrame';
import { SupportTicketImage } from '../models/SupportTicketImage';
import { HttpFile } from '../http/http';

export class SupportTicketCommentDetail {
    'attachment'?: SupportTicketAttachment;
    'frame'?: SupportTicketFrame;
    'image'?: SupportTicketImage;
    'text'?: string;
    'type'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attachment",
            "baseName": "attachment",
            "type": "SupportTicketAttachment",
            "format": ""
        },
        {
            "name": "frame",
            "baseName": "frame",
            "type": "SupportTicketFrame",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "SupportTicketImage",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupportTicketCommentDetail.attributeTypeMap;
    }

    public constructor() {
    }
}
