/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UsageMeteringDimensionMappingMode } from '../models/UsageMeteringDimensionMappingMode';
import { HttpFile } from '../http/http';

export class UsageMeteringDimensionMappingValue {
    /**
    * The convertion multiplier when mapping from the source dimension key to the destination dimensionKey by quantity mode. Not required if the mapping mode is AMOUNT.
    */
    'convertionMultiplier'?: number;
    /**
    * The destination dimension key of the usage metering mapping.
    */
    'dimensionKey'?: string;
    /**
    * The conversion mode of UsageMeteringDimensionMapping. The default is QUANTITY if not available.
    */
    'mappingMode'?: UsageMeteringDimensionMappingMode;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "convertionMultiplier",
            "baseName": "convertionMultiplier",
            "type": "number",
            "format": ""
        },
        {
            "name": "dimensionKey",
            "baseName": "dimensionKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "mappingMode",
            "baseName": "mappingMode",
            "type": "UsageMeteringDimensionMappingMode",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsageMeteringDimensionMappingValue.attributeTypeMap;
    }

    public constructor() {
    }
}


