/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Partner } from '../models/Partner';
import { HttpFile } from '../http/http';

export class UsageMeteringDailyRecord {
    'amount'?: number;
    'date'?: Date;
    /**
    * The Entitlement ID of the usage metering daily record.
    */
    'entitlementID'?: string;
    /**
    * The group bys expression of the usage metering. When the same usage metering key may have multiple expressions of group bys to aggregate the usage.
    */
    'groupBysExpression'?: string;
    /**
    * The dimension key of the usage metering.
    */
    'key'?: string;
    /**
    * The partner where this usage metering daily record is from. Such as AWS, AZURE or GCP.
    */
    'partner'?: Partner;
    'quantity'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "entitlementID",
            "baseName": "entitlementID",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupBysExpression",
            "baseName": "groupBysExpression",
            "type": "string",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "partner",
            "baseName": "partner",
            "type": "Partner",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsageMeteringDailyRecord.attributeTypeMap;
    }

    public constructor() {
    }
}


