/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AwsProductDimension } from '../models/AwsProductDimension';
import { AwsRenewalOfferType } from '../models/AwsRenewalOfferType';
import { CancellationSchedule } from '../models/CancellationSchedule';
import { Contact } from '../models/Contact';
import { LastModifiedBy } from '../models/LastModifiedBy';
import { NotificationEvent } from '../models/NotificationEvent';
import { HttpFile } from '../http/http';

export class WorkloadMetaInfo {
    /**
    * The linked ACE ApnCrmUniqueIdentifier of the private offer if available.
    */
    'aceApnCrmUniqueIdentifier'?: string;
    /**
    * The AWS SaaS product dimensions. Applicable for AWS SaaS products only. This is used to save price info when creating AWS SaaS product.
    */
    'awsSaasProductDimensions'?: Array<AwsProductDimension>;
    /**
    * Original offer ID for Azure Upgrade
    */
    'azureOriginalOfferIDForUpgrade'?: string;
    /**
    * Applicable for AWS Marketplace only, when the IsAgreementBasedOffer is true.
    */
    'baseAgreementId'?: string;
    /**
    * The Suger buyer IDs of the private offer if available.
    */
    'buyerIds'?: Array<string>;
    /**
    * The Chargebee subscription ID of the private offer if available.
    */
    'chargebeeSubscriptionID'?: string;
    /**
    * The contacts of the offer to notify if any updates.
    */
    'contacts'?: Array<Contact>;
    /**
    * The Suger CPPO_IN offer ID.
    */
    'cppoInOfferId'?: string;
    /**
    * The Suger CPPO offer ID. Reseller to end buyer
    */
    'cppoOfferId'?: string;
    /**
    * The Suger CPPO_OUT offer ID. ISV to reseller
    */
    'cppoOutOfferId'?: string;
    /**
    * The custom meta info of the offer can be updated by seller via API or console.
    */
    'customMetaInfo'?: { [key: string]: string; };
    /**
    * If enabled, Suger will test metering the usage for this entitlement hourly.
    */
    'enableTestUsageMetering'?: boolean;
    /**
    * The cancellation schedule for the entitlement. It is nill if no cancellation schedule.
    */
    'entitlementCancellationSchedule'?: CancellationSchedule;
    /**
    * The error messages when the offer is invalid or offer related tasks failed. This is the raw error messages from the offer related tasks.
    */
    'errorMessages'?: Array<string>;
    /**
    * Hubsport deal ID of the private offer if available.
    */
    'hubspotDealId'?: string;
    /**
    * The Internal note of the private offer. It is only visible to the seller/ISV, not visible to the buyer. Up to 1000 characters.
    */
    'internalNote'?: string;
    /**
    * Applicable for AWS Marketplace only, If this offer is agreement based offer.
    */
    'isAgreementBasedOffer'?: boolean;
    /**
    * If this offer is an Azure upgrade offer.
    */
    'isAzureUpgradeOffer'?: boolean;
    /**
    * Whether the gross revenue is fully synced for the entitlement.
    */
    'isGrossRevenueFullSync'?: boolean;
    /**
    * Applicable for AWS Marketplace only. If this offer is renewal offer of existing agreement. The existing agreement can be within or outside AWS Marketplace. AWS may audit and verify your offer is a renewal. If AWS is unable to verify your offer, then AWS may revoke the offer and entitlements from your customer.
    */
    'isRenewalOffer'?: boolean;
    /**
    * If this offer is a GCP replacement offer. Applicable for GCP Marketplace replacement offer only.
    */
    'isReplacementOffer'?: boolean;
    /**
    * The user who last modified the product/offer/buyer/contact.
    */
    'lastModifiedBy'?: LastModifiedBy;
    /**
    * The notifications of the offer if any updates. In most cases, it is to notify contacts/buyers when the offer is pending acceptance.
    */
    'notifications'?: Array<NotificationEvent>;
    /**
    * The date when the offer is accepted by the buyer. Only available when the private offer has been accepted.
    */
    'offerAcceptDate'?: Date;
    /**
    * The prettified ErrorMessages. Using AI to make it more readable and understandable. The prettified error messages will be used for the offer related UI display.
    */
    'prettifiedErrorMessages'?: Array<string>;
    /**
    * Applicable for AWS Marketplace only, required when the IsRenewalOffer is true.
    */
    'renewalOfferType'?: AwsRenewalOfferType;
    /**
    * The end time of the replaced offer. Applicable for GCP Marketplace replacement offer only.
    */
    'replacedOfferEndTime'?: Date;
    /**
    * The resource name of the GCP Marketplace offer that this offer is replacing. In format of \"projects/{gcpProjectNumber}/services/{productServiceName}/privateOffers/{privateOfferId}\" Applicable for GCP Marketplace replacement offer only.
    */
    'replacedOfferResourceName'?: string;
    /**
    * The Salesforce entitlement URL
    */
    'salesforceEntitlementURL'?: string;
    /**
    * The Salesforce opportunity ID of the private offer if available.
    */
    'salesforceOpportunityId'?: string;
    /**
    * The test usage metering end time. It is used for test usage metering only. Required if EnableTestUsageMetering is true.
    */
    'testUsageMeteringEndTime'?: Date;
    /**
    * The message to notify when the offer is updated.
    */
    'updateMessage'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "aceApnCrmUniqueIdentifier",
            "baseName": "aceApnCrmUniqueIdentifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "awsSaasProductDimensions",
            "baseName": "awsSaasProductDimensions",
            "type": "Array<AwsProductDimension>",
            "format": ""
        },
        {
            "name": "azureOriginalOfferIDForUpgrade",
            "baseName": "azureOriginalOfferIDForUpgrade",
            "type": "string",
            "format": ""
        },
        {
            "name": "baseAgreementId",
            "baseName": "baseAgreementId",
            "type": "string",
            "format": ""
        },
        {
            "name": "buyerIds",
            "baseName": "buyerIds",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "chargebeeSubscriptionID",
            "baseName": "chargebeeSubscriptionID",
            "type": "string",
            "format": ""
        },
        {
            "name": "contacts",
            "baseName": "contacts",
            "type": "Array<Contact>",
            "format": ""
        },
        {
            "name": "cppoInOfferId",
            "baseName": "cppoInOfferId",
            "type": "string",
            "format": ""
        },
        {
            "name": "cppoOfferId",
            "baseName": "cppoOfferId",
            "type": "string",
            "format": ""
        },
        {
            "name": "cppoOutOfferId",
            "baseName": "cppoOutOfferId",
            "type": "string",
            "format": ""
        },
        {
            "name": "customMetaInfo",
            "baseName": "customMetaInfo",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "enableTestUsageMetering",
            "baseName": "enableTestUsageMetering",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "entitlementCancellationSchedule",
            "baseName": "entitlementCancellationSchedule",
            "type": "CancellationSchedule",
            "format": ""
        },
        {
            "name": "errorMessages",
            "baseName": "errorMessages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "hubspotDealId",
            "baseName": "hubspotDealId",
            "type": "string",
            "format": ""
        },
        {
            "name": "internalNote",
            "baseName": "internalNote",
            "type": "string",
            "format": ""
        },
        {
            "name": "isAgreementBasedOffer",
            "baseName": "isAgreementBasedOffer",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isAzureUpgradeOffer",
            "baseName": "isAzureUpgradeOffer",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isGrossRevenueFullSync",
            "baseName": "isGrossRevenueFullSync",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isRenewalOffer",
            "baseName": "isRenewalOffer",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isReplacementOffer",
            "baseName": "isReplacementOffer",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastModifiedBy",
            "baseName": "lastModifiedBy",
            "type": "LastModifiedBy",
            "format": ""
        },
        {
            "name": "notifications",
            "baseName": "notifications",
            "type": "Array<NotificationEvent>",
            "format": ""
        },
        {
            "name": "offerAcceptDate",
            "baseName": "offerAcceptDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "prettifiedErrorMessages",
            "baseName": "prettifiedErrorMessages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "renewalOfferType",
            "baseName": "renewalOfferType",
            "type": "AwsRenewalOfferType",
            "format": ""
        },
        {
            "name": "replacedOfferEndTime",
            "baseName": "replacedOfferEndTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "replacedOfferResourceName",
            "baseName": "replacedOfferResourceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "salesforceEntitlementURL",
            "baseName": "salesforceEntitlementURL",
            "type": "string",
            "format": ""
        },
        {
            "name": "salesforceOpportunityId",
            "baseName": "salesforceOpportunityId",
            "type": "string",
            "format": ""
        },
        {
            "name": "testUsageMeteringEndTime",
            "baseName": "testUsageMeteringEndTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updateMessage",
            "baseName": "updateMessage",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WorkloadMetaInfo.attributeTypeMap;
    }

    public constructor() {
    }
}


